### ISSUE TITLE
Error - Unranked?

### ISSUE THREAD

**Issue by Eniplay** [BenFradet/RiotSharp#100]
Hey,

I have a new Error, but its Actually more a Question:

when i Ask for the league with:

var tier = test[0].Tier.ToString();

it always returns: "Error 404, Resource not found".

could this be because the Summoner/s is/are unranked?

**Comment by BenFradet** [comment]
Yup exactly.

**Comment by Eniplay** [comment]
So i just have to make a loopß 
if tier = NULL than write Unranked or something liek that?

**Comment by BenFradet** [comment]
It's up to you to handle it however you want.

**Comment by Eniplay** [comment]
Well thanks again :)
i try this.

**Comment by BenFradet** [comment]
No problem.
