### ISSUE TITLE
recent games showing only 10 games..

### ISSUE THREAD

**Issue by itapi** [BenFradet/RiotSharp#101]
is it posibble to show more games?

**Comment by BenFradet** [comment]
Hey, no this is a limitation from Riot.

**Comment by itapi** [comment]
ty bro so how does lolking and other lol stats websites works? they just send a web reqquest to the official lol website and get the html?

**Comment by BenFradet** [comment]
To be honest I don't know if those websites have stopped scraping the official website.

**Comment by itapi** [comment]
ah... thank u bro :smiley:  and one last question-in my code i display the new free champ rotation every week but i goltta get all champs,use foreach and check if they are free to play.
its very long... like check 120+ champs attributes.. and i just saw you can get only free champs easily in on request- https://eune.api.pvp.net/api/lol/eune/v1.2/champion?freeToPlay=true&api_key=2549a36f-ad08-4774-8097-40867bd001e4...

wouldnt it make it easier?

**Comment by BenFradet** [comment]
True, I don't know why I haven't implemented it earlier, I'll create a new issue and will implement it in the 2.2.

**Comment by Corran-Raisu** [comment]
@itapi @BenFradet : To the best of my knowledge, places like lolking, lolnexus, op.gg and such have switched over to the API with the exception of features revolving around producing Replays (as in op.gg) / Spectator (as in lolnexus) functionality. 

Past that they still use (i believe) client bots that essentially connect to the same service anyone else does using the pvp.net lobby.  Nothing is pulled from the website.

If I remember correctly, they needed to make these changes (along with LoLNexus's removal of indicators showing who in a match were from a premade group) to be in compliance with Riot's Terms of Service. 

There is a link regarding this somewhere in the developer.riotgames.com boards but I can't look for it at this time.

**Comment by BenFradet** [comment]
Interesting, thanks @Corran-Raisu

**Comment by BenFradet** [comment]
Closing
