### ISSUE TITLE
Championbans/ Current Gamestats

### ISSUE THREAD

**Issue by Mascerude** [BenFradet/RiotSharp#103]
Is it possible to get Championbans of the current Game + Dragon kills?

**Comment by Mascerude** [comment]
Or Maybe get Access on the ingame chat

**Comment by BenFradet** [comment]
Hey, it's possible to get the banned champions and the number of dragon kills for each team with:

```c#
var api = RiotApi.GetInstance("api_key");
var match = api.GetMatch(Region.euw, matchId);
foreach (var team in match.Teams)
{
  foreach (var bannedChampion in team.Bans)
  {
    Console.WriteLine(bannedChampion.ChampionId);
  }
  Console.WriteLine(team.DragonKills);
}
```

However, it's not possible to access the ingame chat.

**Comment by Mascerude** [comment]
Hmm i mean at the current game , because i am working for a little group of caster and we want to add a drakecounter and a banstats while during the pick and ban phase

**Comment by BenFradet** [comment]
As far as I can tell the available games in the match history for a specific summoner are all completed games, sorry.

**Comment by itapi** [comment]
@BenFradet  hey ! i didnt know u can get current game stats... :smiley:  cool.

btw how or where can i get the matchid bro?

**Comment by Corran-Raisu** [comment]
@itapi : when you use Summoner.GetMatchHistory or Summoner.GetRecentGames you're returned a List<MatchSummary> or List<Game> respectively

MatchSummary.MatchId and Game.GameId give you the Id you use for GetMatch() 

    Summoner mySummoner = api.GetSummoner(Region.na, 00000000);
        List<RiotSharp.MatchEndpoint.MatchSummary> myMatchHistory =
            mySummoner.GetMatchHistory(0, 14,
              null, 
              new List<Queue> { Queue.RankedSolo5x5 });
        foreach (MatchSummary myMatchSummary in myMatchHistory)
        {
              MatchDetail myMatchDetail = api.GetMatch(myMatchSummary.Region, myMatchSummary.MatchId, true);
              //Do things with myMatchDetail to collect detailed data about the match.
        }

Also, he was saying that you can't get Current Game information since its not part of the API (yet, hopefully) and that you can only obtain data on completed games.

**Comment by BenFradet** [comment]
Hey, I don't think this will ever happen since you could get unfair information about the other team like buff timers for example.

**Comment by itapi** [comment]
@Corran-Raisu  yeahh bro thats if u want to get details after the match... but i want to get the current match id.. to get current match stats...
how is it posibble??!?!

**Comment by BenFradet** [comment]
As said previously it's not possible.

**Comment by itapi** [comment]
@BenFradet  oh... i understand... thanks bro :)

**Comment by Corran-Raisu** [comment]
@BenFradet "Live Game Data" yes you are correct.

However, my basis for why there could potentially be a Current Game API is that you can already get information like that (albeit with more effort) through using the Spectator client (at a 3 minute delay of course). An API would similarly have a 3 minute delay.

**Comment by BenFradet** [comment]
@Corran-Raisu  Well in that case that might be feasible but I don't see them making an API like that available anytime soon.

**Comment by BenFradet** [comment]
Closing.

**Comment by GersuAlves** [comment]
Ja é possível essa api?
há alguns sites como br.op.gg que tem essa capacidade.

**Comment by JanOuborny** [comment]
@GersuAlves Please ask your question in English. Otherwise, we can't help you.
