### ISSUE TITLE
Participant should include highestAchievedSeasonTier

### ISSUE THREAD

**Issue by StevenReitsma** [BenFradet/RiotSharp#104]
See https://developer.riotgames.com/api/methods#!/930/3215

The participants in a match each include an attribute highestAchievedSeasonTier indicating their border. This attribute is not included in the Participant class.

**Comment by StevenReitsma** [comment]
Looks like this is the only thing that needs to be added to RiotSharp.MatchEndpoint.Participant for this to work:

        /// <summary>
        /// Highest achieved season tier.
        /// </summary>
        [JsonProperty("highestAchievedSeasonTier")]
        public Tier HighestAchievedSeasonTier { get; set; }

**Comment by BenFradet** [comment]
Yup feel free to submit a pull request.

**Comment by StevenReitsma** [comment]
Sure, give me a second!

**Comment by BenFradet** [comment]
No problem.

**Comment by StevenReitsma** [comment]
Hmm, seems like the value can actually be "UNRANKED" which is not a valid value for the Tier enum. How do you propose to fix this? Would it be better to create a separate enum or to add the Unranked tier to the class? Alternatively a check in the GetMatchHistory method could set the Tier attribute to null if it's changed to a Tier? nullable type.

**Comment by BenFradet** [comment]
I think it might be best to add unranked to the existing Tier class.

**Comment by StevenReitsma** [comment]
Okay I have the commit ready but I'm not at home right now. I'll submit a pull request tomorrow.

**Comment by BenFradet** [comment]
Ok great.
