### ISSUE TITLE
[CurrentGame Endpoint] New Riot API endpoint for summoner's current game

### ISSUE THREAD

**Issue by mfioccop** [BenFradet/RiotSharp#107]
As of 1/29 there is a new endpoint available for the API.  It gets data from the spectator grid to retrieve the current game a summoner is playing in.

I've already gone ahead and started adding support for this endpoint, it's in my fork of the repo.  I followed the same standards as the other implemented endpoints to the best of my knowledge.  All calls to the endpoint are getting a 503 response (Riot server problem), so I'll try testing it more later when their end is up and running again.

**Comment by BenFradet** [comment]
Great, please pr the develop branch and not the master as this will be part of 2.2

**Comment by BenFradet** [comment]
Closing because of #108, great work.
