### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by Eniplay** [BenFradet/RiotSharp#109]
Hello,

I have a problem. SOMETIMES, when i start a request my programm gives back an error message.
Here is the code:

 		    var api = RiotApi.GetInstance("KEY");
                    var summoner = api.GetSummoner(RiotSharp.Region.euw, name);//Here is the Error

                    string sum_lv = summoner.Level.ToString();
                    string sum_pp = summoner.ProfileIconId.ToString();

                    pictureBox1.ImageLocation = "http://ddragon.leagueoflegends.com/cdn/5.2.2/img/profileicon/" + sum_pp + ".png";
                    pictureBox1.Visible = true;
                    textBox2.Text = sum_lv;

The Error tells me this:"A first chance exception of type 'System.NullReferenceException' occurred in RiotSharp.dll". What is the problem?
Thanks for help :)
~Hermann

**Comment by BenFradet** [comment]
Hey, do you know on which ```name``` the exception occurs?

**Comment by Eniplay** [comment]
i get it from a textbox. you write the summoner name in there, press the button and that whats in this textbox, will be now in the string name.

**Comment by BenFradet** [comment]
Yeah I gathered that, but don't you have any example name raising an exception?

**Comment by Eniplay** [comment]
well sometimes, when i start the programm, enter a name and press the button i get All informations. no problem. but next time i start the programm, exacctly this problem occurs. 
It doesnt matter if i write instead of "name" the summoner name itself.

**Comment by StevenReitsma** [comment]
This might be due to a WebException in Requester.GetResponse. I believe this has to do with the fact that the HTTP service on EUW is very unstable. While I'm writing this the EUW API HTTP service is offline while the HTTPS API is functioning normally.

**Comment by AbhayaGH** [comment]
Hi there,

I got this 'System.NullReferenceException' when server refused the connection. Replacing 'http' by 'https' solved the problem. However, in the requester, the 'HandleWebException' throws this nullreference when this is not a WebException but a SocketException one.

I think a test if 'response' is not null before analysing 'HttpWebResponse.StatusCode' could send the original exception instead of the null one.

Sorry if i don't propose a patch but i just created my account to post here and i'm not confident with GitHub so i wouldn't like to mess your code... ^^

**Comment by Eniplay** [comment]
Hey,
So i should include an exception, if 

 var summoner = api.GetSummoner(RiotSharp.Region.euw, name);

gives back an null value?

**Comment by Eniplay** [comment]
well, now it shows me this message:

![503](https://cloud.githubusercontent.com/assets/10630916/6105859/3a501928-b05c-11e4-9342-337ed24b2444.png)

**Comment by StevenReitsma** [comment]
@AbhayaGH if the server refuses a connection the GetResponse method will still throw a WebException, not a SocketException.
@Eniplay the EUW API is still offline, you can see this on the Riot status page. This has nothing to do with RiotSharp. But yes, putting a try-catch block around GetSummoner is what you want to do anyway. This is by design and not a bug.

**Comment by AbhayaGH** [comment]
@StevenReitsma You are right and i was not clear enough, GetResponse throw a WebException if server refuses to connect. However, in this case, the WebException.Response is null. So when the HandleWebException method tries to extract the WebException.Response.StatusCode, it throws a NullReferenceException.
The WebException has in this case an InnerException of type SocketException.

@Eniplay You can use the Riot API web page to test the request (you will get JSON response in return) and then found out where does the problem come from.

**Comment by StevenReitsma** [comment]
Ah! That makes sense. I'll try and see what I can do.

**Comment by AbhayaGH** [comment]
Looks good
i did something like this in the version i have, in case exception is not connection refused:

[...]
HttpWebResponse response = (HttpWebResponse)ex.Response;

if (response == null)
    throw new RiotSharpException(ex.Message, ex);

switch (response.StatusCode)
{
[...]

**Comment by BenFradet** [comment]
Yup, I'll try to fix that in master during the week

**Comment by h1pp0** [comment]
Hello,

I just started using this wonder framework today and I noticed there is an issue with the NA region url.

The current implementation sends the requests over http. However, all http requests to the NA server over http fail with "Unable to connect to the remote server". 

Changing the http to https in line 40 and 45 of Requester.cs fixes the issue for NA region.

**Comment by BenFradet** [comment]
Hey, see #111.

**Comment by BenFradet** [comment]
The nuget is updated.
