### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by DMedo** [BenFradet/RiotSharp#110]
When I try to get summoner with 
_apiInstance.GetSummonerAsync(region, name);
for any region and any name it just returns 400 bad request.
It's not api key because it works over riots site. Could it be something with http and https? I saw it in another thread.

Also I have try - catch around that code, but this error doesn't get caught which is weird if you ask me.

**Comment by BenFradet** [comment]
Yup, we're looking into it.

**Comment by DMedo** [comment]
Others have reported it?

**Comment by BenFradet** [comment]
Yes, should be fixed by Friday.

**Comment by DMedo** [comment]
Thanks, great work btw

**Comment by BenFradet** [comment]
Thanks, I'll let you know when it's fixed.

**Comment by BenFradet** [comment]
See #111

**Comment by DMedo** [comment]
I tried to update nuget package but it doesn't do anything

**Comment by BenFradet** [comment]
Haven't had the chance to update the nuget yet.

**Comment by BenFradet** [comment]
The nuget is updated.

**Comment by DMedo** [comment]
thanks
