### ISSUE TITLE
summoner.getRecentGames JsonSerializationException

### ISSUE THREAD

**Issue by XanderBras** [BenFradet/RiotSharp#116]
in var recentGames = summoner.getRecentGames();
I get:

JsonSerializationExcept was unhandled.
An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll
Additional information: Error setting value to 'SubType' on RiotSharp.GameEndpoint.Game

**Comment by BenFradet** [comment]
This is due to the new CouterPick game type, this has been fixed in #113, I'll update the nuget during the day.

**Comment by BenFradet** [comment]
Do you still encounter the issue?

**Comment by BenFradet** [comment]
Assuming fixed.
