### ISSUE TITLE
Latest Newtonsoft.Json

### ISSUE THREAD

**Issue by suklje** [BenFradet/RiotSharp#117]
Trying to add RiotSharp to Windows Phone 8.1 project fails, because WP is not supported in Json 6.0.1. 

Can you update to the latest Newtonsoft.Json 6.0.8, or is this something I can do myself? 

Thanks and keep it up!

**Comment by BenFradet** [comment]
Hey,

Thanks for the heads-up, I'll schedule that for 2.2 which should be done in a week or so.

**Comment by BenFradet** [comment]
This is done in develop.

**Comment by suklje** [comment]
Thank you, looking forward to the release.

**Comment by BenFradet** [comment]
@suklje 2.2 is out.

**Comment by suklje** [comment]
Thank you!

Kudos also for the NuGet package. Unfortunately this problem arises when adding the RiotSharp targeting Windows Phone 8.1:

install-package : Could not install package 'RiotSharp 2.2.0'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content fi
les that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ install-package RiotSharp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by BenFradet** [comment]
Hey, sorry for the late response. This is because the library is not compatible with windows phone apps. I'll create a new issue for converting the library into a portable class library which would be compatible with both desktop and phone apps.

**Comment by starostin13** [comment]
Which version I can use for Windows Phone 8(.1) Silverlight?

**Comment by BenFradet** [comment]
As of now, it's still not a pcl, I haven't had time to work on that, but it's planned.
