### ISSUE TITLE
eSports API

### ISSUE THREAD

**Issue by mfioccop** [BenFradet/RiotSharp#120]
I noticed a post on the developer forums regarding the lolesports.com API (http://na.lolesports.com/api/swagger), and wondered if you had any intention of adding this to the library?  Not sure how long this API has been up, but it might be nice to include for developers trying to pull data regarding past/current tournaments and professional player statistics.

**Comment by BenFradet** [comment]
Thanks for spotting this one.
There is quite a lot of work to be done, so I won't give you a timeline, but I'll try to work on it.

**Comment by Corran-Raisu** [comment]
Be aware its an unsupported / unofficial API. So it's likely to have some issues and people probably won't get any technical assistance with any problems that the API has.

My best guess is that this is what Riot plans on merging into the official Riot API in some manner when they update the Tournament Code system so those can be used more publicly.

**Comment by BenFradet** [comment]
I decided not to integrate this, since this project is only supporting the official API, closing.
