### ISSUE TITLE
How get detail champion by id ?

### ISSUE THREAD

**Issue by Enzo-bianchi** [BenFradet/RiotSharp#121]
Hello,
I don't know how get the detail of a champion by ID,

With this : var champion = api.GetChampion(RiotSharp.Region.euw, (int)CurrentGame.Participants[0].ChampionId);

I have only some properties about free, ranked enabled etc..

But i saw in StaticEndPoint the class ChampionStatic with id, detail, image... . So how i can acces to this class with the championId get previously ?

Thanks :)
Sorry for my english :/

**Comment by BenFradet** [comment]
Hey,

You can do that with:

```csharp
var staticApi = StaticRiotApi.GetInstance(YOUR_API_KEY);
var champ = staticApi.GetChampion(Region.euw, championId);
```

**Comment by BenFradet** [comment]
Closing as there has been no response for a long time.
