### ISSUE TITLE
Losses in LeagueEntry

### ISSUE THREAD

**Issue by proace137** [BenFradet/RiotSharp#122]
Hi, the api provides a losses entry in the league-v2.5 endpoint. Just add the member in the "LeagueEntry" class.

Im new to github, dont really now how pull requests works.

**Comment by BenFradet** [comment]
Thanks for spotting this one, I'll fix it.

**Comment by BenFradet** [comment]
The nuget has been updated.

**Comment by ChaoticLoki** [comment]
Sorry for reopening this, but I downloaded the latest version of nuget and it still seems like `Losses` are still missing from the `LeagueEntry` class.  A quick peek into the dll that is installed with version 2.2.1 shows

![image](https://cloud.githubusercontent.com/assets/3889658/7317085/41303132-eaaf-11e4-90fc-a735620e2c18.png)

**Comment by BenFradet** [comment]
Weird indeed, let me look into that.

**Comment by BenFradet** [comment]
I must have forgotten something when building the nuget, sorry.
This should be resolved in 2.2.2.

**Comment by BenFradet** [comment]
Assuming resolved, closing.
