### ISSUE TITLE
Uncertain Object Types in StaticDataEndpoint Cause Serialization Errors

### ISSUE THREAD

**Issue by aktai0** [BenFradet/RiotSharp#124]
Specifically, each of these are declared as Object, but during runtime are type Newtonsoft.Json.Linq.JArray which isn't marked as serializable in that Json library:

StaticDataEndpoint.ChampionSpellStatic.Range
StaticDataEndpoint.SpellVarsStatic.Coeff
StaticDataEndpoint.SummonerSpellStatic.Range

These are all types described as "List of Integer or a String", so I don't really know any solution that works for .NET apart from reorganizing the entire hierarchy, or making a hacky workaround class that has both a list of integers and a string.

My current workaround is to set those variables to null before serialization (which works for me because I don't need those for my purposes).

**Comment by BenFradet** [comment]
Yeah, I don't know how to deal with it either.

**Comment by BenFradet** [comment]
Closing as this is by the Riot API's design, not mine, so I can't really do anything about it.
