### ISSUE TITLE
How would I get the player's current division? 

### ISSUE THREAD

**Issue by NhatL** [BenFradet/RiotSharp#125]
I'm almost stumped by this. I found the tiers inside the tier converters, but I'm not sure how to retrieve the current division from the summoner ID. Any idea how?

**Comment by Ijwu** [comment]
I haven't gotten around to using RiotSharp quite yet, but it looks as though you'll need to use the league api for this. My guess, by browsing through the source of RiotSharp, you'll need to get the `Summoner` object for the player you're looking for then using their `Id` retrieve the leagues they are a part of.

Each league has the property `Entries` which is a `List<LeagueEntry>` and you'll likely want to `Select` out the specific entry for the summoner you're looking for in that league.

All together, an example would look like this

```c#
var api = RiotApi.GetInstance("YOUR_API_KEY");

// Get the summoner, I used my own name for this,
var summoner = api.GetSummoner(Region.na, "ijwu");

// Gets all leagues that the summoners provided participate in.
// The summoner.Id object is a long but the `GetLeagues` method takes a list of ints, so some casting is needed.
var allLeagues = api.GetLeagues(Region.na, new List<int>{(int)summoner.Id});

// Since `GetLeagues` returns a `Dictionary<long, List<Leagues>>` we index it with the summoner id.
// After indexing it we use LINQ to select the single league of the `Queue` that we're interested in.
// In this case we want solo queue.
var ranked5v5League = allLeagues[summoner.Id].Where(x => x.Queue == Queue.RankedSolo5x5).Single();

// Now we have a `League` object and we use LINQ to get the `LeagueEntry` which belongs to this summoner. We do that by comparing Ids.
// After getting the correct entry our `Select` pulls out the Division and it's `Single`'d out to a single string.
var division = ranked5v5League.Entries.Where(x => x.PlayerOrTeamId == summoner.Id.ToString()).Select(x => x.Division).Single();
```

Let me know if my conventions are a little wacky when it comes to using this library, I threw this together in a few minutes using LINQPad. It works for me and correctly returns my division. If all the LINQ method calls cause you trouble I'd be happy to elaborate, just let me know.

@BenFradet can let me know if I'm butchering the use of his library or not, haha.

**Comment by NhatL** [comment]
@Ijwu Thanks a lot! That's what I was looking for :) How would I get the tier, as in Diamond/Challenger/Bronze/etc?

**Comment by BenFradet** [comment]
@Ijwu Thanks a lot for your help.

However there is a slightly simpler way to do just that:

```c#
var api = RiotApi.GetInstance("YOUR_API_KEY");

var summoner = api.GetSummoner(Region.euw, "TheSummonerName");

var ranked5v5League = summoner.GetLeagues().Where(l => l.Queue == Queue.RankedSolo5x5).Single();

var division = ranked5v5League.Tier;
```

**Comment by Ijwu** [comment]
@BenFradet I believe @NhatL was asking about division, which is placed inside each entry in `ranked5v5League.Entries`.

I'm glad to help, I'm really enjoying this library.

**Comment by BenFradet** [comment]
My bad.

Then, it would be:

```c#
var api = RiotApi.GetInstance("YOUR_API_KEY");

var summoner = api.GetSummoner(Region.euw, "TheSummonerName");

var ranked5v5League = summ.GetLeagues().Where(l => l.Queue == Queue.RankedSolo5x5).Single();

var div = ranked5v5League.Entries.First().Division;
```

**Comment by NhatL** [comment]
@BenFradet Oh this is a bit simpler as comparing to the previous one ljwu wrote. Thanks :)

Just another thing. I'm making something similar to lolnexus but in wpf. Do you know why making the program retrieve every summoner's info like for lolnexus (http://i.imgur.com/5EL3yjl.jpg) take around 20-30 seconds to complete? Sites like lolnexus takes 5-6 s :\

**Comment by BenFradet** [comment]
How many summoner's info are you trying to retrieve?

Because the API given by Riot is rate limited, with a development API key you can only make 10 request(s) every 10 second(s) or 500 request(s) every 10 minute(s) whichever comes first.

Moreover, RiotSharp takes care of the rate limiting for you, that's why it takes so long.

**Comment by NhatL** [comment]
I'm getting the info for 10 champions. I guess that's where the timing comes from. I just counted and I made around 30-40 API calls, which is why it's taking so long ^_^. Thanks again for the RiotSharp :D

**Comment by BenFradet** [comment]
No problem, I'm just glad to see people are using it.

**Comment by NhatL** [comment]
Sorry for bumping it up, is there a way to retrieve the summoner's rune page in the current match?

**Comment by BenFradet** [comment]
There is, through the [current-game API](https://developer.riotgames.com/api/methods#!/976/3336), which has not been implemented in RiotSharp yet.

I'll try to work on #127 during the week.

**Comment by BenFradet** [comment]
Sure, I'll mention you in this issue once I'm done.

**Comment by BenFradet** [comment]
@NhatL My bad it was already implemented, I'm not the one who did it, that's why I didn't remember :smile: .

To answer your question:

```c#
var api = RiotApi.GetInstance("YOUR_API_KEY");

var myPlatform = Platform.EUW1;
var mySummonerId = 1234;
var currentGame = api.GetCurrentGame(myPlatform, mySummonerId);

var me = currentGame.Participants.Find(
    p => p.SummonerId == mySummonerId);
var myRuneIds = me.Runes.ConvertAll(r => r.RuneId);

// to get more info
var staticApi = StaticRiotApi.GetInstance("YOUR_API_KEY");
var runes = staticApi.GetRunes(Region.euw,
    RiotSharp.StaticDataEndpoint.RuneData.all).Runes.Values;
var runesImInterestedIn = runes.Where(r => myRuneIds.Contains(r.Id));
```

**Comment by NhatL** [comment]
@BenFradet Thank you so much! I'm looking for a way to convert the runesImInterestedIn into a string or array of the rune names, so something like

9x armor pen, 9x armor, 9x MR, 9x AP

Is there a way to get this done? I'm not too sure of how I'm supposed to use runesImInterestedIn. Sorry for all the questions!

**Comment by NhatL** [comment]
@BenFradet  Thank you so much!

Just a question though. What does runesImInterestedIn actually return? Does it convert the IDs in myRuneIDs into names as an array. I want to convert the myRuneIDs into myRuneNames, where for example rune ID 5235 will give the rune Name "+3.85 ability power"

**Comment by BenFradet** [comment]
Closing.
