### ISSUE TITLE
Getting Champion spell images?

### ISSUE THREAD

**Issue by Pierre3557** [BenFradet/RiotSharp#131]
Hi, 

I know this is probably a stupid question, but I saw that there is a property for Image.Full in the StaticApi.GetChampion() method. I'm currently writing a app in Windows Forms and I would like to know if it is possible to display the champion's ability images (Passive and other spells), how I would go around doing it and where I would find the actual images.

I have tried using the images in the Riot folder, but it is a bit problematic seeing as the image names are mixed up and not all of them follow the same rhythm.

Any advice would be appreciated.

Thanks :-)

**Comment by BenFradet** [comment]
Hi,

I'd suggest you read the part about data dragon on the [static data api page](https://developer.riotgames.com/docs/static-data).

**Comment by Pierre3557** [comment]
Hi,

Thanks for the speedy reply.

I will check it out.

Kind Regards,
Pierre van der Westhuizen
Software Developer
T: 078 113 8142

**Comment by BenFradet** [comment]
Have a look at #147 if you still have an issue, I gave a pretty detailed explanation there.
Closing.

**Comment by Pierre3557** [comment]
Dude, you are the best. 

 

Thanks a bunch.
