### ISSUE TITLE
Getting team name and tags for current game?

### ISSUE THREAD

**Issue by Pinouf42** [BenFradet/RiotSharp#133]
Hello, first, you have to know that RiotSharp is awesome ! Thanks for this awesome work.

I would like to be able to get team names and tags from the CurrentGame part but actually it isn't possible. Do you plane to do it? :)

Thank you very much again.

Pinouf.

**Comment by BenFradet** [comment]
Hey, thanks for the kind words.

I'll try to work on RiotSharp next week, I'll keep you updated.

**Comment by Pinouf42** [comment]
Nice, thank you ! :)

2015-06-21 1:32 GMT+02:00 Ben Fradet <notifications@github.com>:

> Hey, thanks for the kind words.
>
> I'll try to work on RiotSharp next week, I'll keep you updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenFradet/RiotSharp/issues/133#issuecomment-113841574>
> .
>



-- 
Julien *PINEY*

**Comment by BenFradet** [comment]
Hi, as per the [API reference](https://developer.riotgames.com/api/methods#!/976/3336), only the ```teamId``` is available on the current game endpoint.

**Comment by Pinouf42** [comment]
Well, that is strange :o when I use the API with raw data (JSON) it gives me the teamTag :o

Anyway thanks for your reply and your time :) !

**Comment by Pinouf42** [comment]
I understand why, that's because its only available in ranked team :/

**Comment by BenFradet** [comment]
Closing.
