### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by DMedo** [BenFradet/RiotSharp#138]
Are exceptions thrown for every non 2XX code?

**Comment by BenFradet** [comment]
AFAIK yes, why?
Do you have an example of a non-2XX code not throwing an exception?

**Comment by DMedo** [comment]
No, I assumed that's the case but wasn't 100% sure. Thanks for quick response.

**Comment by BenFradet** [comment]
No problem.

**Comment by BenFradet** [comment]
Closing.
