### ISSUE TITLE
Interceptor

### ISSUE THREAD

**Issue by murilogibim** [BenFradet/RiotSharp#139]
Hey there,

It would be great to have an Interceptor within the wrappers to be able to get detailed information regarding requests and responses. Something like some events available to subscribe with information like: request url and the raw response data.

<code>public event BeforeSendRequestEventHandler BeforeSendRequest;</code>
<code>public event AfterReceiveReplyEventHandler AfterReceiveReply;</code>

**Comment by BenFradet** [comment]
Great idea, feel free to submit a PR.

**Comment by BenFradet** [comment]
Closing this for now, @murilogibim will reopen if he wants to.
cf #140
