### ISSUE TITLE
Error setting value to 'SubType' on 'RiotSharp.GameEndpoint.Game'.

### ISSUE THREAD

**Issue by uokitomer** [BenFradet/RiotSharp#143]
Hey,

First of all thank you for this tool, I'm having this exception when calling the GetRecentGames method. I know this happends when the Json has been changed by Riot, is it going to be fixed soon?.

Thanks!

Hernán

**Comment by BenFradet** [comment]
This is surely related to #141, so I'd say it's going to be fixed pretty soon.

**Comment by BenFradet** [comment]
It's fixed in dev, I'll let you know once I've updated the nuget.

**Comment by BenFradet** [comment]
I've updated the nuget (now 2.3), tell me if it's fixed.

**Comment by BenFradet** [comment]
Assuming fixed.
