### ISSUE TITLE
need help with sorting champions by Name

### ISSUE THREAD

**Issue by Marquizee** [BenFradet/RiotSharp#145]
There is my code. How can i sort champions by name ?

            var GetChampions = staticApi.GetChampions(currentRegion);
            foreach (var champions in GetChampions.Champions)
            {
                comboBox1.Items.Add(champions.Value.Name);
            }

![image](https://cloud.githubusercontent.com/assets/12690190/9341655/e3fa2e3a-45ff-11e5-84f6-a3257aa1ba00.png)

**Comment by BenFradet** [comment]
Hi,

To sort the champions by name, I'd suggest:

```c#
var champions = staticApi.GetChampions(Region.euw).Champions;
var championsOrdered = champions.OrderBy(c => c.Value.Name);
```

**Comment by Marquizee** [comment]
Thank you a lot !
