### ISSUE TITLE
Error setting value to 'PlayerStatSummaryType' on 'RiotSharp.StatsEndpoint.PlayerStatsSummary'.

### ISSUE THREAD

**Issue by Marquizee** [BenFradet/RiotSharp#146]
I can't understand why do i get this error.
Same problem with #83. 
When I am searching for summoner name "Marquizee" i have no problems, but when i'm trying another summoner name i have an error.

                    var summaries = summonerName.GetStatsSummaries();
                   
                    var soloqSummary = summaries.Where(summary => summary.PlayerStatSummaryType == RiotSharp.StatsEndpoint.PlayerStatsSummaryType.RankedSolo5x5).FirstOrDefault();

How can i solve this ?

**Comment by BenFradet** [comment]
Hey,

Do you mind giving me a name of summoner with which it doesn't work so I can reproduce the error?

**Comment by Nigolasy** [comment]
I'm getting this error, when using unranked Summoners. Just try to catch it and post if it worked.

**Comment by BenFradet** [comment]
Nevermind, I've been able to reproduce the issue on my own, I'm investigating.

**Comment by BenFradet** [comment]
I've found the issue, Bilgewater wasn't yet in PlayerStatsSummaryType, will fix soon.
