### ISSUE TITLE
Getting summoner spells images from current game

### ISSUE THREAD

**Issue by audi0slave** [BenFradet/RiotSharp#147]
Hi Ben,
First I have to thank you in advance for saving me so much time working on a parser for the Riot Api.

I would like to know, if possible, how to get the summoner spells images from current game taking in mind that "CurrentGameParticipant" object from "current-game" returns the spell ID, and the "SummonerSpellDto" object from the static api does not have any method which I can pass that ID as parameter. 

Please let me know if my question is not clear, since english is not my first language and its a little hard to ask these technical stuff.

Thank you for your time.

Daniel

**Comment by BenFradet** [comment]
Hey, thanks for the kind words.

Let's imagine I have 31 as a spell id, I would do something along those lines:

```c#
var spells = staticApi.GetSummonerSpells(
  Region.euw,
  RiotSharp.StaticDataEndpoint.SummonerSpellData.image);
var spellId = 34;
var spell = spells.SummonerSpells.First(s => s.Value.Id == 31);

Console.WriteLine(spell.Key);
Console.WriteLine(spell.Value.Id);
Console.WriteLine(spell.Value.Image.Full);
Console.WriteLine(spell.Value.Image.Group);
```

`spell.Value.Image.Full` gives you a file name (the spell image's name) and `spell.Value.Image.Group` give you another part of the url which you can contain to obtain the full url of the image:

```c#
var imageUrl = "http://ddragon.leagueoflegends.com/cdn/5.2.1/img/" +
  spell.Value.Image.Group + "/" + spell.Value.Image.Full;
```

which gives you ![someicon](http://ddragon.leagueoflegends.com/cdn/5.2.1/img/spell/SummonerPoroThrow.png).

I suggest you take a look at the documentation page regarding the static API [here](https://developer.riotgames.com/docs/static-data).

**Comment by audi0slave** [comment]
Thanks @BenFradet 
I didn't realize how to use that kind of methods since there are a few things about the recent .net framework that didn't understand well.

Thanks to your reply I realize I had to learn a few extra things regarding to Linq, Dictionaries and that kind of stuff.

Thanks again for your time and your work.

Sincerely,
Daniel.

**Comment by BenFradet** [comment]
Glad I could help.
