### ISSUE TITLE
NullReferenceException in GetMatchHistory()

### ISSUE THREAD

**Issue by Andi07** [BenFradet/RiotSharp#148]
So i want to acces the mach-history of a summoner with the GetMatchHistory()- function, but i get a NullReferenceException for the Return Statement of the GetMatchHistory()-function

So i start with
```C#
  LoL_Api = new League_of_Legends_functions("Raikawee");  // Start the Api  with the given Summoner

          
 // Get The Match List, and here is the Error

  List <RiotSharp.MatchEndpoint.MatchSummary> matchSummaries = LoL_Api.GetMatchList(); 
```

and my GetMatchList()-function symply returns the MatchHistory like
```C#
        public List<RiotSharp.MatchEndpoint.MatchSummary> GetMatchList()
        {
            List<RiotSharp.MatchEndpoint.MatchSummary> mHistory = summoner.GetMatchHistory();
            return mHistory;
        }
```

So the statement I get the NullReferenceException would be
```C#
return JsonConvert.DeserializeObject<PlayerHistory>(json).Matches;
```

I can use the GetRecentGames()-function which means that the Api is basically working.

**Comment by BenFradet** [comment]
Hey,

This is because [the match history endpoint has been deprecated in favor of the match list endpoint](https://developer.riotgames.com/discussion/community-discussion/show/iz34oFti).

I'll try to remove it from RiotSharp soon.
