### ISSUE TITLE
 Error setting value to 'Season'

### ISSUE THREAD

**Issue by ArcaneWater** [BenFradet/RiotSharp#149]
Few days ago i started to receive  Error setting value to 'Season' when calling GetMatch... Any idea whats wrong?

**Comment by BenFradet** [comment]
I'm guessing there is a new season, i'll check that out and keep you posted

**Comment by ArcaneWater** [comment]
Thanks, i checked a bit and yea it seems there is a new field season and some changes.

**Comment by ArcaneWater** [comment]
Thanks for update! When does update come on Nuget package?

**Comment by BenFradet** [comment]
In a few minutes, I'll post there when I'm done.

**Comment by BenFradet** [comment]
It's been uploaded and it's getting indexed https://www.nuget.org/packages/RiotSharp/2.3.1

**Comment by ArcaneWater** [comment]
Hmm is it correct version uploaded? I just updated it and again received the same error for seasons,, but if i build myself dll. then it works ok..

**Comment by BenFradet** [comment]
Weird, I'll look into it.

**Comment by ArcaneWater** [comment]
So is it confirmed?

**Comment by BenFradet** [comment]
Yes, I must have uploaded the wrong nuget.

**Comment by ArcaneWater** [comment]
Great forgot to ask, is the correct one now uploaded?

**Comment by BenFradet** [comment]
Not right noe, no.
I'll try to upload the right one tonight.

**Comment by BenFradet** [comment]
I've uploaded a new package, it should be fixed.

**Comment by BenFradet** [comment]
@ArcaneWater, Is this fixed on your side?

**Comment by ArcaneWater** [comment]
Yes fixed thanks! Closing

**Comment by BenFradet** [comment]
No problem.
