### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Duciel** [BenFradet/RiotSharp#150]
Maybe I'm missing something big but here are the steps I've done so far :
- Downloading your sources
- Generating the DLL
- Adding it to the references of my project

My project is almost only your tutorial linked on a button :

``` C#
var api = RiotApi.GetInstance("YOUR_API_KEY", your_rate_limit_per_10s, your_rate_limit_per_10m);
try
    {
         var summoner = api.GetSummoner(Region.euw, "StopOFlop");
    }
catch(RiotSharpException ex)
    {
        //Handle the exception however you want.
    }
```
I'm having an issue at this line (well to be exact no, but this line is returning null so JsonConvert can't deserialize it)
``` C#
var json = requester.CreateRequest(
        string.Format(SummonerRootUrl, region.ToString()) +
        string.Format(ByNameUrl, Uri.EscapeDataString(summonerName)),
    region);
```
I digged a bit into it and I found that the request is created nicely, but when the response is asked [Requester.CreateRequest() => GetResponse()] it returns null.

The exact error is :
```
Exception thrown : 'System.NullReferenceException' in RiotSharp.dll (translated from french)
```
Maybe you can provide me some help with my error, I can give you more informations if needed.

**Comment by BenFradet** [comment]
Hey,

I haven't been able to reproduce this issue with the following code

```c#
var api = RiotApi.GetInstance("MY_API_KEY");

var summoner = api.GetSummoner(Region.euw, "StopOFlop");
```

Can you give me more details?

**Comment by Duciel** [comment]
Here is what i use :
- Visual Studio 2015
- Windows 8.1
- Using my compagnie's network (might have some problem accessing data due to firewall or something tho, will try at home tonight)

Here are the steps I made :
- Downloading the .zip from GitHub
- Generating the sources (release) in visual studio
- Creating a new C# project, creating a button on the windows form and adding the code in my previous post
- Adding the references from your .dll (riot api and the other one)

There is no compilation error, only when running.

I'll try on another computer this evening, will give you further information once it's done.

**Comment by BenFradet** [comment]
To be honest, I have no idea.
I don't think it's the issue but have you tried using the api directly on [developer.riotgames.com](https://developer.riotgames.com/) with your api key?

**Comment by Duciel** [comment]
Currently at home, did the exact same thing, it's actually working, might be a problem with windows 8 or the network at my office, trying to duplicate the working project and copy it at office tomorrow. Will give you further details tomorrow :)

**Comment by BenFradet** [comment]
If you can access the nuget, it remains the simplest way.

**Comment by Duciel** [comment]
Found my answer. It's due to the network from my office, they are probably blocking the api call. Maybe it could be a good idea to send a message in case someone can't access the net (not connected or blocked like me) could save him some time :)

I took my laptop from work to home and everything is working. You can close my subject.

Thank you for your time.

**Comment by BenFradet** [comment]
No problem, thank you for using the lib.
