### ISSUE TITLE
Reduce the number of warnings

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#162]
Reduce the number of warnings outputted by the ci.
For example: https://ci.appveyor.com/project/BenFradet/riotsharp/build/2.3.3.13

**Comment by Ostrea** [comment]
I am not sure that it helped, according to [this](https://ci.appveyor.com/project/BenFradet/riotsharp/branch/develop) there are still 1591 warnings

**Comment by BenFradet** [comment]
The messages are [here](https://ci.appveyor.com/project/BenFradet/riotsharp/branch/develop/messages)

**Comment by Ostrea** [comment]
Yeah and I still have all warnings related to missing docs

**Comment by BenFradet** [comment]
Yeah [this line](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotSharp.csproj#L29) should have been `<NoWarn>CS1591</NoWarn>`.

I didn't review your changes carefully enough sorry.

**Comment by Ostrea** [comment]
Are you sure about it? Stackoverflow says it should be just 1591

**Comment by BenFradet** [comment]
Welp, I'll try out both tomorrow.

**Comment by Ostrea** [comment]
Also please try /p:nowarn=1591 as paramater for msbuild

**Comment by BenFradet** [comment]
I thought about it and I think we should limit the removal of warnings only regarding the following classes:

  - [IRiotApi](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/IRiotApi.cs)
  - [IStaticRiotApi](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/IStaticRiotApi.cs)
  - [IStatusRiotApi](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/IStatusRiotApi.cs)
  - [ITournamentRiotApi](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/ITournamentRiotApi.cs)

with:

```c#
#pragma warning disable 1591
// the interfaces
#pragma warning restore 1591
```

because the others are legitimate warnings.

**Comment by Ostrea** [comment]
Will do it. But will it stop CI from showing them?

**Comment by BenFradet** [comment]
It should, yes.

**Comment by Ostrea** [comment]
I have done it and made new pull request #216

**Comment by BenFradet** [comment]
Great, I'll have a look later today.
