### ISSUE TITLE
Do not create additional providers during unit tests

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#184]
It's been asked by Riot not to create additional providers in the unit tests.

pinging @StevenReitsma @jvanvugt, if you have ideas on how to proceed.

**Comment by StevenReitsma** [comment]
I figured there was a chance that could happen. The problem is that the only way to create tournaments and tournament codes is to be the owner of the provider (i.e. same API key). You can use your API key to create a single provider and use that in testing, but the test will only work for you.

**Comment by StevenReitsma** [comment]
It's strange that they ask this by the way, since creating a provider with the exact same callback URL and region returns the same provider ID, indicating it doesn't get created again.

**Comment by BenFradet** [comment]
Yup, I'll ask them.

**Comment by BenFradet** [comment]
Problem solved, I discussed the issue with them and since we're not creating additional providers they're going to let us keep the api key.
