### ISSUE TITLE
Dynamic Queue Type Missing From Queue.cs and QueueConverter.cs

### ISSUE THREAD

**Issue by KreepN** [BenFradet/RiotSharp#191]
The introduction of dynamic queue breaks JSON.Net's ability to deserialize any matches tied to the new dynamic queue system.

The new queue type "TEAM_BUILDER_DRAFT_RANKED_5x5" was added.

Sample JSON:

   "region":"NA",
         "platformId":"NA1",
         "matchId":2073287371,
         "champion":412,
         "queue":"TEAM_BUILDER_DRAFT_RANKED_5x5",
         "season":"SEASON2016",
         "timestamp":1453329688907,
         "lane":"BOTTOM",
         "role":"DUO_SUPPORT"

**Comment by BenFradet** [comment]
This has already been added in #190

**Comment by haefele** [comment]
Is there already a date set when a new update will be released containing this changes?
Currently it's really hard to use RiotSharp because you always stumble upon matches with the new queue types.
And since there is no updated release you get exceptions all the time... :cry:

**Comment by KreepN** [comment]
If you pull from the develop branch you can utilize all the accepted fixes. That's what I did/do, and it all works fine.

**Comment by BenFradet** [comment]
Unfortunately, I'm on holidays until next week so it won't be until then, sorry.

**Comment by haefele** [comment]
Hmm, alright. Seems like I have to make my own NuGet package, at least until a update comes out. Thanks for your help.
