### ISSUE TITLE
CurrentGameEndpoint Converters is missing Dynamic Queue GameQueueTypes

### ISSUE THREAD

**Issue by marineaua** [BenFradet/RiotSharp#197]
I was trying to call .GetCurrentGame() with the new queue type and it was throwing JsonSerializationException. Studied the files and recent commits and turns out there was two more Enums missing.

This is my first time pushing/calling issue to any open source project so forgive me if I am doing this incorrectly.

Really great project by the way hope to push more towards you!

**Comment by BenFradet** [comment]
Thanks for noticing, I'll have a look at the pr later today.
