### ISSUE TITLE
Support for Team Builder

### ISSUE THREAD

**Issue by abraaocaldas** [BenFradet/RiotSharp#199]
Hello, There is any ETA for support of TEAM_BUILDER_DRAFT_RANKED_5x5 ?

Best Regards.

**Comment by BenFradet** [comment]
This has been added in #198 and #193 but I'm unfortunately on holidays and unable to publish a nuget, until February 29th.

However you're free to build from develop in the meantime.

**Comment by BenFradet** [comment]
It should be in 2.4.1 which has been released yesterday.
Let me know if you encounter any issues.
