### ISSUE TITLE
Issue accessing  RiotSharp.LeagueEndpoint.LeagueEntry

### ISSUE THREAD

**Issue by Belterius** [BenFradet/RiotSharp#200]
Hello,
First of all, thank you for your awesome work, it's really helpfull for any c# beginner.

I would like to get a player Division and Tier, managed to get the tier using summoner.GetEntireLeagues and then .Tier but I can't seem to find a way to retrieve a RiotSharp.LeagueEndpoint.LeagueEntry where the division seems to be present.

Did I miss something or is there no way to get the Division of a player ?
Thanks you.

**Comment by SuperNoobishDude** [comment]
Here's a little bit of my code to take as an example.
Hope it helps.

var summoner = api.GetSummoner(Region.euw, "SuperNoobishDude").GetLeagues();
            summonerName = summoner[0].Name.ToString();
            summonerTier = summoner[0].Tier.ToString();
            summonerDivision = summoner[0].Entries[0].Division.ToString();
            summonerLP = summoner[0].Entries[0].LeaguePoints.ToString();

**Comment by Belterius** [comment]
I get it now, thank you for your help !

**Comment by BenFradet** [comment]
You can also check #125, closing.
