### ISSUE TITLE
Get champions free to play unit tests are failing

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#204]
For some reason:
  - [GetChampions_FreeToPlay_Test](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharpTest/RiotApiTest.cs#L165)
  - [GetChampionsAsync_FreeToPlay_Test](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharpTest/RiotApiTest.cs#L175)

are returning 12 champions instead of the expected 10 which are returned in normal use of the api

**Comment by Ostrea** [comment]
They are okay on my local machine. Maybe unignore them and try on CI?

**Comment by BenFradet** [comment]
Thanks for the update, I'll try that out tomorrow.
