### ISSUE TITLE
Replace all Converters folder by Enums

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#215]
In the different endpoints, there is a `Converters` folder like for [the tournament api](https://github.com/Ostrea/RiotSharp/tree/ChangeLobbyEventType/RiotSharp/TournamentEndpoint/Converters).

Since those folders contain both enums and associated json converters, I think it'd be better if they'd be named `Enums`.

**Comment by Ostrea** [comment]
Maybe split them to two different folders?

**Comment by BenFradet** [comment]
Yup, it might indeed be better to split them into two different folders.

**Comment by Ostrea** [comment]
So one folder `Converters` with converters and other one `Enums` with enums?

**Comment by BenFradet** [comment]
What would be even better, I think, would be to put the converter in the same file as the enum and have only one `Enums` folder.

What do you think?

**Comment by Ostrea** [comment]
They are quite big, I think it will clutter enums definitions. What about placing `Converters` folder inside `Enums` folder?

**Comment by BenFradet** [comment]
Yup, that seems like the best thing to do.
