### ISSUE TITLE
request matchlist api parameter error

### ISSUE THREAD

**Issue by QiushiZhu** [BenFradet/RiotSharp#220]
`Matchlist getMatchlist(long summonerId,[int? startindex])`
the type of startindex should be long instead of int.

**Comment by Ostrea** [comment]
Are you sure about it? `beginIndex` and `endIndex` are `int` in [docs](https://developer.riotgames.com/api/methods#!/1069/3683)

**Comment by QiushiZhu** [comment]
That's int. My fault. Sorry for bad request.Please close this issue.

**Comment by BenFradet** [comment]
No problem.
