### ISSUE TITLE
Tests regarding shard status are failing

### ISSUE THREAD

**Issue by Ostrea** [BenFradet/RiotSharp#223]
Here is the exception:

> Newtonsoft.Json.JsonSerializationException:
 Error converting value "570d6bcbc9fe2901006ac7be" to type 'System.Int64'. Path 'services[0].incidents[0].updates[0].id', line 1, position 320. ---> System.FormatException: Input string was not in a correct format.

**Comment by BenFradet** [comment]
[In the doc](https://developer.riotgames.com/api/methods#!/908/3142) the id is supposed to be a long but apparently it's not.

The fix should only be to replace `long` by `string` in [the Message's id field](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StatusEndpoint/Message.cs#L37).

**Comment by BenFradet** [comment]
@Ostrea do you want to take it or should I?

**Comment by Ostrea** [comment]
If you want to do it right now then do or else I can try it tomorrow.

**Comment by BenFradet** [comment]
No problem I'll do it now then, thanks for reporting it though!
