### ISSUE TITLE
SummonerId is always zero when navigating to Participants from FeaturedGame

### ISSUE THREAD

**Issue by jessanmen1** [BenFradet/RiotSharp#226]
If you navigate the list of participants of a featured game, the SummonerId always retrieves zero.

I have attached an example of this behavior:
![image](https://cloud.githubusercontent.com/assets/6974499/14714762/821c1b8e-07e6-11e6-88c3-87bc520539c5.png)

![image](https://cloud.githubusercontent.com/assets/6974499/14714829/db4c9abc-07e6-11e6-8a3e-8c1f4282d847.png)

![image](https://cloud.githubusercontent.com/assets/6974499/14714873/02d0bc44-07e7-11e6-964c-7431120a1727.png)

**Comment by BenFradet** [comment]
Hey, thanks for catching that, I'll investigate.

**Comment by jessanmen1** [comment]
Hi,

Thanks for the prompt response. As long as I know, you cannot extract that field from Participants.

I mean, as I can see you are mapping that field from the JSON in the Participants class:

![image](https://cloud.githubusercontent.com/assets/6974499/14716465/7a79e044-07ed-11e6-8884-f1c9670d419d.png)

But if you have a look in the API, that field does not exist. Look:

![image](https://cloud.githubusercontent.com/assets/6974499/14716512/af2f9df6-07ed-11e6-8f92-c49ddb3effdc.png)


I think that's basically the issue. Hope it helps.

Regards.

**Comment by BenFradet** [comment]
That does seem to be the problem, do you want to open a PR and remove the field or should I?

**Comment by jessanmen1** [comment]
Do it by yourself :) I'll try to collaborate with this project in the future.

Thanks for this awesome work!

**Comment by BenFradet** [comment]
No problem, thanks again for finding out.
