### ISSUE TITLE
Rename none to basic in the static api

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#231]
The `none` enum values for the static API in [DataRequested](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticDataEndpoint/DataRequested.cs) should be renamed to `default` as this is a more fitting name.

**Comment by shrayasr** [comment]
`default` is a C# keyword though. Are we OK with using `@default` instead?

**Comment by BenFradet** [comment]
oops forgot about that, `@default` seems a bit weird, maybe we should name it `base` or `basicinfo`, what do you think?

**Comment by shrayasr** [comment]
> what do you think?

How about something like `basic` ? Since each of the static APIs has some set of basic return keys.

**Comment by BenFradet** [comment]
`basic` LGTM

**Comment by shrayasr** [comment]
:+1: Shall I update #218 to have both this and the documentation changes as well?

**Comment by BenFradet** [comment]
Nope, I think opening a separate PR would be better.

**Comment by shrayasr** [comment]
Yeah makes sense. Another PR sounds good.
