### ISSUE TITLE
Replace default version in the static endpoints

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#235]
The default version in [the different static endpoints](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticRiotApi.cs) need to be replaced by the empty string since this will default to the latest available version.

**Comment by BenFradet** [comment]
It should also be replaced in `IStaticRiotApi`

**Comment by matodt** [comment]
Appears resolved in [243](https://github.com/BenFradet/RiotSharp/pull/243)

**Comment by BenFradet** [comment]
Apparently slipped through the cracks, thanks for catching that.
