### ISSUE TITLE
MvvM

### ISSUE THREAD

**Issue by Xqzmeplz** [BenFradet/RiotSharp#240]
Hello,

is there any chance to implement the INotifyPropertyChanged for the public classes?
I would assume there are some mobile developers using the MVVM Pattern in connection with this beautiful API. But if you want to set an Binding from an control (e.g. Label) to an value (e.g. Summoner Name) you can not retrieve the values via the NotifyPropertyChanged event. At the moment you have to build proxy classes which provide, for each public field, this event.

Would you consider this as an improvment?

**Comment by BenFradet** [comment]
This seems to me like a definitive improvement! Feel free to implement it and open a PR.

**Comment by Xqzmeplz** [comment]
Hi @BenFradet,

i am sorry it took me a while to answer. I had much to do at work so, yeah.
All of a sudden i guess i made a major mistake. No one would actually do stuff like change the summoner name property of an summoner instance. If the summoner changes you simply request a new one via the service (this example applies to all other public fields and values). As long as you don't manipulate the public fields of the classes it does not make any sense to add the INotifyPropertyChanged to the classes.

Sorry waisting your time, keep up the good work :)

**Comment by BenFradet** [comment]
No problem, thanks for the kind words.
