### ISSUE TITLE
Typing Inconsistency With summonerId

### ISSUE THREAD

**Issue by EvanZimmerman** [BenFradet/RiotSharp#242]
I am unsure if I am allowed to raise an issue so sorry if I am out of place here.  I recently dove into this project and made a test class. I was wondering why the summonerId is defined as a long, yet the majority of calls referencing a summonerId requires it to be an integer? A simple cast fixes this problem but I can't seem to find a reason for why it is implemented like this. 

Here is an example method that raises my confusion found in RiotApi.cs:135

```public List<Summoner> GetSummoners(Region region, List<int> summonerIds)``` 

Thanks in advanced!

**Comment by EvanZimmerman** [comment]
So... Apparently I overlooked the Pull Requests showing the changes in typing for this.  My apologies for lack of detail!!!

**Comment by BenFradet** [comment]
Hey Evan,

You're definitely allowed to create issues!

However, I'm wondering which pulk request you're referring to?

**Comment by EvanZimmerman** [comment]
It was in PR #206!

**Comment by BenFradet** [comment]
Indeed, I think I should take over this PR since the maintainer doesn't seem to be working on it anymore.
