### ISSUE TITLE
The tournament api related tests are failing

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#247]

**Comment by matodt** [comment]
Not sure if you are still messing with this, but I will probably be touching this code a lot setting up mocks.

**Comment by BenFradet** [comment]
I haven't add time to look into it but I guess there is something wrong with my api key.

**Comment by matodt** [comment]
If it is an issue with the api key, mocking the requester will remove this issue.

**Comment by BenFradet** [comment]
yup :+1:

**Comment by StevenReitsma** [comment]
Feel free to ping me if you have questions regarding the implementation of the tournament API. The organization of our annual tournament is starting soon so I'll have some time reserved for development.

**Comment by matodt** [comment]
Unfortunately I have a large part of the unit test project disassembled at the moment and nothing in a useful format for someone else.  Pretty much took a sledgehammer to it to remove the reliance dependencies.

**Comment by BenFradet** [comment]
Apparently my tournament API key had been disabled by Riot.
I just asked for a new one.
