### ISSUE TITLE
Status wrong type

### ISSUE THREAD

**Issue by BGVzz** [BenFradet/RiotSharp#248]
Hey,

thanks for this amazing work, but I noticed that the type of the Id in Status > Services > Incidents should be string and not long.

**Comment by BenFradet** [comment]
Hey,

Great catch, I think they must have changed the type recently.

Do you want to open a pull request?

**Comment by BGVzz** [comment]
Hey,

I am very new to github, I don't know how to do one..

**Comment by BGVzz** [comment]
Ok, I think I did it.
