### ISSUE TITLE
Move const URL strings into configs

### ISSUE THREAD

**Issue by matodt** [BenFradet/RiotSharp#250]
While [these URLs](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticRiotApi.cs) aren't super likely to change (as it'd be a breaking change for the Riot API), I think we should move them into a config so they can be more easily changed.  We could also take this opportunity to do some refactoring, perhaps adding these to a data structure instead of having individual variables for each of them.

**Comment by BenFradet** [comment]
I don't know about this to be honest. It'd be awkward to pass a config to the different apis to retrieve the urls, what do you think?

**Comment by matodt** [comment]
I guess for a class library it doesn't make a lot of sense.  I am not a fan of a bunch of const strings in two of the class files.

**Comment by matodt** [comment]
This can be closed.  As part of my dependency refactoring I am moving them into an object, so while they will still be kinda ugly, they will all be in one place.

**Comment by BenFradet** [comment]
ok :+1:
