### ISSUE TITLE
Error setting value to 'PlayerStatSummaryType' on 'RiotSharp.StatsEndpoint.PlayerStatsSummary'

### ISSUE THREAD

**Issue by Andrioshe** [BenFradet/RiotSharp#252]
`Error setting value to 'PlayerStatSummaryType' on 'RiotSharp.StatsEndpoint.PlayerStatsSummary'.`

Searched Summonername = "Invictis", "xRikuto" and more

**Comment by BenFradet** [comment]
A `PlayerStatSummaryType` might have been added, feel free to add it.

**Comment by BenFradet** [comment]
This is fixed as of last commit 👍
