### ISSUE TITLE
GetMatchList returns null reference (sometimes)

### ISSUE THREAD

**Issue by XavierLOTJ** [BenFradet/RiotSharp#254]
Using the call `api.GetMatchList(RiotSharp.Region.na, SummonerId)` is returning null about 50% of the time. This should be a synchronous call that doesn't unblock until a result is retrieved, correct? If I click the button to call this a few times, it usually ends up succeeding a couple of times.

Am I missing something, or is this an issue with the package?

[Edit: Seems like GetMatch is doing the same, but a little less frequently]

**Comment by BenFradet** [comment]
There might be an issue with the package since it hasn't been updated for quite some time and a few things have changed since then.

I'll try having a look.

**Comment by BenFradet** [comment]
After investigation, this is because of the lack of update regarding the package and random 429s.

I'd suggest building from source.
