### ISSUE TITLE
Error setting value to 'GameQueueType' on 'RiotSharp.CurrentGameEndpoint.CurrentGame'

### ISSUE THREAD

**Issue by Dewrano** [BenFradet/RiotSharp#275]
Hi,
Using 'GetCurrentGame' to look up Flex Queue games currently prompts the following error: 

> An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll

> Additional information: Error setting value to 'GameQueueType' on 'RiotSharp.CurrentGameEndpoint.CurrentGame'.

The gameQueueConfigId for Flex Queue is 440. I've tested it myself, and I can confirm that it works.
Hope it helps!

**Comment by BenFradet** [comment]
I thought I added e very flex-related enum but apparently not.

Thanks for raising an issue, I'll try to fix it asap.

**Comment by BenFradet** [comment]
This should be fixed in develop

**Comment by Dewrano** [comment]
Hi,
Thank you very much. Now that the new SoloQ is finally out (gameQueueConfigId for SoloQ is 420), I've noticed it being assigned as TeamBuilderRankedSolo in the code. You can still look up games with the new SoloQ Ranked Queue, so it's not like it's broken, it's just the wrong name assigned for the above ID. Very minor issue (if you see it that way!), so I thought you'd still like to see it getting sorted out.

Thank you!

**Comment by BenFradet** [comment]
To be honest, I'm just trying to follow [the game constants](https://developer.riotgames.com/docs/game-constants) as closely as possible.

In those constants, 420 is defined as TEAM_BUILDER_RANKED_SOLO.

**Comment by Dewrano** [comment]
Ah, okay. Thank you!
