### ISSUE TITLE
Multiple summoner is too much ?

### ISSUE THREAD

**Issue by Phobie53** [BenFradet/RiotSharp#282]
Hello, I'm trying to get 5 different summoner statistics.
I got an array of string with their name. Then, in a loop I do :
`var summoner = api.GetSummoner(RiotSharp.Region.euw, pseudos[i]);
                    var stats = summoner.GetStatsSummaries()
                                .Where(s =>
                                    s.PlayerStatSummaryType == PlayerStatsSummaryType.RankedSolo5x5
                                //|| s.PlayerStatSummaryType == PlayerStatsSummaryType.RankedTeam5x5
                                );`

It's working for the first summoner on the loop, but after : RiotSharp.RiotSharpException: 404, Resource not found. It's a limitation from the API Key ?

**Comment by BenFradet** [comment]
a 404 usually means that the summoner simply couldnt be found.

**Comment by EnzChe** [comment]
But I tested : 
Summoner1 then Summoner2
Result : Summoner1 is returned, Summoner2 404

Then I switched and Summoner2 is returned and Summoner1 is 404.

**Comment by BenFradet** [comment]
That is indeed very weird.

In the past I also had random 404s for things which actually existed.

However, what you could do is retrieve all their ids in a single call with, maybe you'll have better luck:

```c#
var names = api.GetSummoners(Region.euw, pseudos);

for (pseudo in pseudos)
{
  // ...
}
```

**Comment by BenFradet** [comment]
I'll close this, feel free to reopen it if you have more info.
