### ISSUE TITLE
Exception being thrown in RiotSharp.RiotApi.GetMatchList

### ISSUE THREAD

**Issue by hunterjw** [BenFradet/RiotSharp#289]
Looks like an issue similar to #275. The following exception is being thrown on line 957 in RiotApi.cs:

`An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll Additional information: Error setting value to 'Queue' on 'RiotSharp.MatchEndpoint.MatchReference'.`

The data returned as a json string seems to be correct but as soon as it attempts to deserialize the string to a MatchList object, the exception is thrown. One possible cause could be that the server is sending the string "TEAM_BUILDER_RANKED_SOLO" as one of the queue types but there isn't a value in the queue enum that matches this.

**Comment by BenFradet** [comment]
Are you using the last published nuget or you built RiotSharp yourself from develop?

**Comment by hunterjw** [comment]
I encounter the exception in both the latest nuget package and when I build from the develop branch.

**Comment by BenFradet** [comment]
Mmh ok, I'll investigate tomorrow.

**Comment by hunterjw** [comment]
I took a look at it should be resolved with pull request #290.
