### ISSUE TITLE
Make GetSummonersAsync send requests asnychronously

### ISSUE THREAD

**Issue by MingweiSamuel** [BenFradet/RiotSharp#291]
Looking at https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#L168

Wouldn't it be possible to make each call to `requester` non-synchronous (remove the `await`) so that all requests get sent out at the same time, then await them all at once before recombining the results?

I tested with a list of almost 4,000 summoner ids. With a direct single call to `GetSummonersAsync`, it takes about 6.3 seconds, but when I group the summoners into groups of 40 and call `GetSummonersAsync` ~100 times all at once, it takes about 2.3 seconds. (Using production API key so the rate limit wasn't an issue.)

Snippet of code I used to test:

    var tasks = SummonerIds.Select((v, i) => new { v, i })
        .GroupBy(x => x.i / 40)
        .Select(x => riotApi.GetSummonersAsync(Region.na, x.Select(y => y.v).ToList()))
        .ToList();
    await Task.WhenAll(tasks);

**Comment by BenFradet** [comment]
Good idea, please open a PR.

**Comment by MingweiSamuel** [comment]
#299
