### ISSUE TITLE
Rate limiting blocks all regions

### ISSUE THREAD

**Issue by MingweiSamuel** [BenFradet/RiotSharp#296]
I was looking at the way rate limiting works, and it looks to me that when one region is blocked, it causes other regions to block (there is only one semaphore instance: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RateLimitedRequester.cs#L51 )

I wrote a bit of test code below, and the output seems to match.

        [TestMethod]
        [TestCategory("RiotApi")]
        public async Task TestRateLimit()
        {
            var sw = new Stopwatch();
            sw.Start();

            var euwTasks = summonerIds.Take(11).Select(
                s => api.GetSummonerAsync(Region.euw, s));
            var euwTask = Task.WhenAll(euwTasks).ContinueWith(
                res => Console.WriteLine("EUW: " + sw.Elapsed));

            var naTask = api.GetSummonerAsync(Region.na, 69009277).ContinueWith(
                res => Console.WriteLine("NA: " + sw.Elapsed));

            await naTask;
            await euwTask;
        }

.

    NA: 00:00:11.1279019
    EUW: 00:00:11.2118027

Somewhat related issue, the `while(timer) {}` loops are almost certainly sub-optimal unless I am missing something. `HandleRateLimit()` should probably use `Task.Delay(...).Wait()` or `Thread.Sleep(...)`, and there should probably be a `HandleRateLimitAsync()` which uses `await Task.Delay(...)`. I can make a PR if I'm not missing anything.

**Comment by BenFradet** [comment]
Yup, feel free to open a PR.
