### ISSUE TITLE
The binary RiotSharp.dll is built in debug mode.

### ISSUE THREAD

**Issue by JobRapati** [BenFradet/RiotSharp#297]
When testing my app with the Windows Apps Certification Kit I get the error that RiotSharp.dll is built in debug mode. And I have no clue on how to fix this.

**Comment by BenFradet** [comment]
Weird I usually build in rel, must have been an oversight on my end.

I'll try to get that fixed asap.

**Comment by BenFradet** [comment]
I haven't forgotten about this issue but I'm currently moving and I don't have windows with me.

**Comment by BenFradet** [comment]
2.5.1 has been released in Rel mode 👍

**Comment by MingweiSamuel** [comment]
It seems `QueueType.TeamBuildRankedSolo` is still missing from 2.5.1?

**Comment by BenFradet** [comment]
Those were added in 21ae34f, so they should be in the assembly.

**Comment by mentorfloat** [comment]
@BenFradet This is now back again? `The binary RiotSharp.dll is built in debug mode.`
I cloned and built the local nuget with `dotnet pack /p:Configuration=Release` and WACK test still came up with the above.
