### ISSUE TITLE
RANKED_PREMADE_3x3 missing in queue enum

### ISSUE THREAD

**Issue by proace137** [BenFradet/RiotSharp#302]
Got an error when I called the matchlist endpoint when one summoner got "queue":"RANKED_PREMADE_3x3" in his matchlist.

Even in the riot documentation this queue is not included.

This is the call:

https://euw.api.pvp.net/api/lol/euw/v2.2/matchlist/by-summoner/20094017?beginTime=1479440561048&endTime=1479487031100&api_key=###

**Comment by BenFradet** [comment]
Thanks for reporting.

**Comment by jhwee** [comment]
Per https://developer.riotgames.com/docs/game-constants this queue and a few more are deprecated. However, I was able to duplicate the issue -- should we fix?

**Comment by BenFradet** [comment]
Yup, every fix is good to have :+1:
