### ISSUE TITLE
Region missing in MatchReference

### ISSUE THREAD

**Issue by proace137** [BenFradet/RiotSharp#303]
Somtimes it can happen that player switched servers / regions (e.g tr to euw).
For those players you have to have the Region property in the MatchReference(matchlist endpoint) to make the right GetMatch call.

**Comment by BenFradet** [comment]
Good idea.

**Comment by jhwee** [comment]
@BenFradet Is this just a matter of adding the Region property into the MatchReference class? 

I guess I don't see how this will get populated with any other value than the region you pass in to the GET request: `/api/lol/{region}/v2.2/matchlist/by-summoner/{summonerId}`

**Comment by BenFradet** [comment]
@jhwee yup :+1: 

> I guess I don't see how this will get populated with any other value than the region you pass in to the GET request: /api/lol/{region}/v2.2/matchlist/by-summoner/{summonerId}

Agreed but we never know

**Comment by jhwee** [comment]
Thanks. I'll do a PR soon. Riot Games API Status shows matchlist-v2.2 down as of now when I ran the unit test. I will try and confirm again later.
