### ISSUE TITLE
GetCurrentGame() error when playing Ranked Game

### ISSUE THREAD

**Issue by hawezo** [BenFradet/RiotSharp#304]
Hi,

When I try to get the CurrentGame endpoint for a summoner, if he is playing in ranked, I get an error:

> Error setting value to 'GameQueueType' on 'RiotSharp.CurrentGameEndpoint.CurrentGame'.

If the summoner is playing a normal game, it works properly.
The InnerException says that "Object reference not set to an instance of an object".

Here is the stacktrace:
>   à Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   à RiotSharp.RiotApi.GetCurrentGame(Platform platform, Int64 summonerId)
   à LeagueCompanion.Core.Riot.GetCurrentGame(Summoner summoner) dans D:\Développement\.NET\Projets\[C#] League Companion\League Companion\Core\Riot.cs:ligne 78
   à LeagueCompanion.MainWindow.<>c__DisplayClass2_1.<LoadGameAsync>b__1() dans D:\Développement\.NET\Projets\[C#] League Companion\League Companion\MainWindow.xaml.cs:ligne 61
   à System.Threading.Tasks.Task`1.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()

Because of that I can't retrieve informations of a ranked game, while the normal ones are working.
Thanks

**Comment by BenFradet** [comment]
Thanks for reporting, I'll try to have a look.

**Comment by jhwee** [comment]
@hawezo Is this still an issue? I wasn't able to duplicate and I checked against a summoner in a ranked game. I also cross-checked the documentation with the GameQueueType and they seem to be all there.

**Comment by hawezo** [comment]
I changed my code in order to avoid that issue. Currently I can't check if it's still blocking, so I suggest you to not close the ticket.
I'll post as soon as I can check it out

**Comment by BenFradet** [comment]
Any updates on this @hawezo ?

**Comment by BenFradet** [comment]
I'm gonna close this, feel free to reopen @hawezo
