### ISSUE TITLE
Change enums to strings for *Type fields

### ISSUE THREAD

**Issue by MingweiSamuel** [BenFradet/RiotSharp#307]
The enum types, `QueueType`, `GameType`, etc, cause a lot of stability issues because Riot changes the strings returned by the API relatively frequently and without prior notice.

I propose changing the representation of `*Type`s to `string` (instead of enum), and storing the known values as `const`s in static helper classes.

>Hijacking the top post for the table - Ben

|Desired type|Current enum|
|:---:|:---:|
|String|:heavy_check_mark:[GameQueueType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/CurrentGameEndpoint/Enums/GameQueueType.cs)<br>:heavy_check_mark:[GameSubType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/GameEndpoint/Enums/GameSubType.cs)<br>:heavy_check_mark:[QueueType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/MatchEndpoint/Enums/QueueType.cs)<br>[Season](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/MatchEndpoint/Enums/Season.cs)<br>:heavy_check_mark: [Queue](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/MatchListEndPoint/Enums/Queue.cs)<br>:heavy_check_mark: [GameMode](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/GameMode.cs)<br>[Platform](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Platform.cs)<br>:heavy_check_mark: [Slug](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Slug.cs)<br>:heavy_check_mark:[ParTypeStatic](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticDataEndpoint/Champion/Enums/ParTypeStatic.cs)<br>~~PlayerStatsSummaryType~~ (Stats endpoint deprecation)|
|Enum|[Tier](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/LeagueEndpoint/Enums/Tier.cs)<br>[every enum in the MatchEndpoint except QueueType and Season](https://github.com/BenFradet/RiotSharp/tree/develop/RiotSharp/MatchEndpoint/Enums)<br>[GameType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/GameType.cs)<br>[Lane](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Lane.cs)<br>[MapType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/MapType.cs)<br>[Region](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Region.cs)<br>[Role](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Role.cs)<br>[Language](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Language.cs)<br>[TagStatic](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticDataEndpoint/Champion/Enums/TagStatic.cs)<br>[everything in the tournament endpoint](https://github.com/BenFradet/RiotSharp/tree/develop/RiotSharp/TournamentEndpoint/Enums)|

**Comment by hawezo** [comment]
I approve that since I got an error because of this. I think it's even a priority.

**Comment by BenFradet** [comment]
It's indeed a good idea :+1:

As time went by, all those enums slowly became unmanageable.

**Comment by jono-90** [comment]
I wouldn't mind grabbing this one however I'm a bit confused about the scope of this change.
Should this apply to all enums or just those that are getting big and/or frequently changing?

Also, changing the type to string means that a converter class is no longer needed as there's no need to convert from Enum. If the converter isn't needed, the wrapper can simply take the returned text value and store it. As a result, a list of all possible returned values doesn't really need to be maintained. 

I don't see how replacing enums with strings solves the issue of managing returned values when riot changes their API unless the enums are removed all together. But that might not be the desired direction.

Happy to hear your thoughts and discuss this further.

**Comment by BenFradet** [comment]
As you have guessed this would impact the ever-changing enums to ease the maintenance cost.

I think most of the enums would be concerned if we want a clean cut.

It'd be great to hear other people's opinion on this issue since this would be pretty drastic.

**Comment by MingweiSamuel** [comment]
Things to definitely change to strings:
- Anything related to QueueType
- Anything related to GameMode

Things to not change to strings:
- Regions
- Ranks/Tiers (probably)

Not sure about other things:
- Seasons
- Lanes/roles, playstyle
- Event/ward/tower types
- etc

**Comment by BenFradet** [comment]
Here's what I've compiled:

|Desired type|Current enum|
|:---:|:---:|
|String|[GameQueueType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/CurrentGameEndpoint/Enums/GameQueueType.cs)<br>[GameSubType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/GameEndpoint/Enums/GameSubType.cs)<br>[QueueType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/MatchEndpoint/Enums/QueueType.cs)<br>[Season](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/MatchEndpoint/Enums/Season.cs)<br>[Queue](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/MatchListEndPoint/Enums/Queue.cs)<br>[GameMode](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/GameMode.cs)<br>[Language](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Language.cs)<br>[Platform](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Platform.cs)<br>[Slug](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Slug.cs)<br>[ParTypeStatic](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticDataEndpoint/Champion/Enums/ParTypeStatic.cs)<br>[PlayerStatsSummaryType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StatsEndpoint/Enums/PlayerStatsSummaryType.cs)|
|Enum|[Tier](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/LeagueEndpoint/Enums/Tier.cs)<br>[every enum in the MatchEndpoint except QueueType and Season](https://github.com/BenFradet/RiotSharp/tree/develop/RiotSharp/MatchEndpoint/Enums)<br>[GameType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/GameType.cs)<br>[Lane](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Lane.cs)<br>[MapType](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/MapType.cs)<br>[Region](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Region.cs)<br>[Role](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Role.cs)<br>[TagStatic](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticDataEndpoint/Champion/Enums/TagStatic.cs)<br>[everything in the tournament endpoint](https://github.com/BenFradet/RiotSharp/tree/develop/RiotSharp/TournamentEndpoint/Enums)|

Do you guys agree?

**Comment by MingweiSamuel** [comment]
Looks good to me. I think maybe `MapType` should be string but doesn't really matter

**Comment by BenFradet** [comment]
The problem with `MapType` is that it's an int which way clunkier to deal with than an Enum imo

**Comment by MingweiSamuel** [comment]
Ah makes sense

**Comment by JanOuborny** [comment]
I would leave `Season` and `Platform` as enums, because both types rarely change. Having them strongly typed avoids ParameterExceptions, which could be introduced by the use of strings.

**Comment by JanOuborny** [comment]
@BenFradet What do you think, are we done here?

**Comment by BenFradet** [comment]
@JanOuborny what do you think about:

- [Season](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/MatchEndpoint/Enums/Season.cs)
- [GameMode](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/GameMode.cs)
- [Platform](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Platform.cs)
?

**Comment by JanOuborny** [comment]
I would keep `Season` as an enum, because it changes like twice a year.

`GameMode` is already a string and I would keep it that way.

And finally `Platform` changes almost never, but at the same time it makes a lot of methods typesafe.

**Comment by BenFradet** [comment]
Then at the very least `GameMode` needs to be removed

**Comment by JanOuborny** [comment]
I wouldn't remove it. Right now it just a class full of constant string which represent the possible game mode values.

**Comment by BenFradet** [comment]
What's the purpose of having dead code?

**Comment by JanOuborny** [comment]
I rather use constants in my conditions thanstring values, which can be hard to track.

**Comment by BenFradet** [comment]
My bad I thought the converter was still there, closing 👍
