### ISSUE TITLE
Rate limit not handled

### ISSUE THREAD

**Issue by hawezo** [BenFradet/RiotSharp#308]
Hi,
I got issues with the GetLeagues() method from SummonerBase.cs. I cloned the repo and searched from myself what could have caused the error, which is:
> Could not convert string 'status' to dictionary key type 'System.Int64'. Create a TypeConverter to convert from the string to the key type object. Path 'status', line 2, position 10.

It appears that the JSON response code is the following:
```json
{
	"status": {
		"message": "Rate limit exceeded",
		"status_code": 429
	}
}
```

Actually I'm trying to get the participants of a game in order to retrieve their elo, so what I'm doing is:
> Getting the CurrentGame object
Looping through Participants of the CurrentGame object
Getting the summoner corresponding to the Participant.SummonerName with GetSummoner
Getting his leagues with GetLeagues()

And that often crashes at this point, where I guess I get that error. So I'm going to add a pause or something, but just to say the rate limit is not handled.

[See this screenshot.](https://i.imgsafe.org/6969685040.png)

**Comment by BenFradet** [comment]
It most likely comes from Riot and not RiotSharp.

**Comment by hawezo** [comment]
I don't really think so. I think, since I'm doing like 10 requests in a row, that something is wrong with the rate limit handler.
I may be wrong in what I'm saying, but I don't know why it'd come from Riot. When I'm pausing between the requests, I do not get this thing anymore.

**Comment by BenFradet** [comment]
I've encountered this behaviour (Riot not honouring the rate limit) countless times so my guess is that it's on their side.

I might be wrong but the rate limiter has failed me less than the API itself. However, if you think there is a real problem with the rate limiter, feel free to investigate.

**Comment by hawezo** [comment]
Well, I trust you. I'll put an eye to the rate limiter, although you look confident about it.

**Comment by BenFradet** [comment]
Which version of RiotSharp are you using?

We've made some recent changes that might have changed things a bit.

**Comment by hawezo** [comment]
I'm using RiotSharp 2.9.365.1657. I had to download RiotSharp instead of getting it from NuGet because the NuGet's version gave me somme issues about ranked queues.

**Comment by BenFradet** [comment]
Can you try with 2.5.1?

**Comment by MingweiSamuel** [comment]
I also get 429s a lot even when playing around with 300 req/sec production key, don't even get close to that. I feel like it may have something to do with simultaneous requests coming from the same IP, but that is just a hunch and I haven't tested it further.

**Comment by MingweiSamuel** [comment]
Or maybe it is from sending the same request multiple times. For example here I just sent the request ~3-4 times, and it gave a 429: http://i.imgur.com/w5iOiyJ.png

https://developer.riotgames.com/docs/rate-limiting Documentation doesn't provide much info, and the response didn't have a `X-Rate-Limit-Type` header like it should

**Comment by BenFradet** [comment]
Closing.

**Comment by MingweiSamuel** [comment]
#378
