### ISSUE TITLE
GetChallengerLeagues with the summoners position in the League

### ISSUE THREAD

**Issue by JobRapati** [BenFradet/RiotSharp#312]
When I'm getting the Challenger league from any of the regions it appears that the order in which they are gotten is not the same as the position of in the Challenger league.

For example Entry 0 is not position 1 in the challenger league.

Would anyone have an idea on how to achieve the desired result?

**Comment by BenFradet** [comment]
Do you get the same results interacting with the API directly on https://developer.riotgames.com/?

**Comment by JobRapati** [comment]
Yes indeed, sorry for making it look like it's yours/RiotSharps fault will ask on other locations as well.

Thanks for your response, should have tested this myself first.

**Comment by JobRapati** [comment]
Fixed it, just had to order them right now ordering them by there LP might need some more ordering to get a more accurate display but for the sake of right now it works good enough.

**Comment by BenFradet** [comment]
:+1:
