### ISSUE TITLE
Can't get 2017 Ranked Games list (MatchList)

### ISSUE THREAD

**Issue by jono-90** [BenFradet/RiotSharp#315]
Possibly due to the Queue / QueueType issues, or Riot is having issues with the API on their end.

The GetMatchList function requires a 'Queue' parameter and none of these work (RankedSolo5x5, TeamBuilderDraftRanked5x5 in the Queue Enum)

Also, Riots API MatchList documentation says that the "ranked queue" param is optional, however it is a required param in the GetMatchList function. Is there a way to get a list of all matches from all queues?

**Comment by jono-90** [comment]
Additionally, I'm aware that Riot is currently having issues with the MatchList endpoint not returning for the SEASON2017 queue type. I'm using the 'BeginTime' param to get games from this season.

It works natively:
https://oce.api.pvp.net/api/lol/oce/v2.2/matchlist/by-summoner/972756?beginTime=1481108400000&api_key=...

but not using RiotSharp.

**Comment by BenFradet** [comment]
I'm not sure what you mean by:

> Also, Riots API MatchList documentation says that the "ranked queue" param is optional, however it is a required param in the GetMatchList function.

since rankedQueues is optional cf https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#L899-L902.

Regarding only using beginTime what keeps you from doing:

```c#
api.GetMatchList(Region.oce, 972756, beginTime = new DateTime(yourDate))
```

?

**Comment by jono-90** [comment]
Ah thanks for clearing that up, I misread the code. I'm quite new here, sorry if I'm off the mark on this.

In essence that is statement I was running, it should work, however I'm still hitting an error. I believe it has something to do with the new queue enums (for some reason they don't appear on my end). I'm using 2.5.1.

I noticed this:
<img width="215" alt="riotsharp package" 
src="https://cloud.githubusercontent.com/assets/1514750/22586930/70a0d2b4-ea53-11e6-9d65-9d235664a7f0.png">

The error is:
An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll
Additional information: Error setting value to 'Queue' on 'RiotSharp.MatchEndpoint.MatchReference'.

Could there be a versioning issue with the nuget package?

**Comment by BenFradet** [comment]
That's weird, there are definitely missing queues with 2.5.0 so make sure you use 2.5.1.

Also, the RANKED_PREMADE queue has been added recently (cf #313) and no versions of RiotSharp published on nuget have it yet.

If you still get the same issue with 2.5.1, the solution would be to build off of the develop branch.

**Comment by jono-90** [comment]
Building from develop works :) - cheers

**Comment by BenFradet** [comment]
No problem :+1:

**Comment by BenFradet** [comment]
closing
