### ISSUE TITLE
ı cant use season 2017 pls help

### ISSUE THREAD

**Issue by Ejdersoy** [BenFradet/RiotSharp#316]
![error](https://cloud.githubusercontent.com/assets/20680870/22661421/01bb13f2-ecae-11e6-9e10-fbfaf790c726.png)
ı need season 2017 but not working As you can see in the photo season3 is not working please help me.

**Comment by Ejdersoy** [comment]
ı am tring this 
api.GetMatchList(Region.oce, summoner.Id, beginTime = new DateTime(01.01.2017));
but it is not working too it say :
" begin time is not exist in the current context"

**Comment by BenFradet** [comment]
You need to update the RiotSharp nuget because support for the 2017 season has been added only in the latest versions.

**Comment by Ejdersoy** [comment]
Version is 2.5.1. it isnt lastest version ?

**Comment by BenFradet** [comment]
My bad, there is no nuget containing the 2017 season, you'll have to build RiotSharp yourself from develop.

It's been added in 1ccd0596982ca82ff8b4618e75cd1939aa4171ec.

**Comment by BenFradet** [comment]
clsoing
