### ISSUE TITLE
Error setting value to 'GameMode' on 'RiotSharp.GameEndpoint.Game'

### ISSUE THREAD

**Issue by villam98** [BenFradet/RiotSharp#318]
Hi,
Using 'GetRecentGames' to look up recent games currently prompts the following error:

An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll

Additional information: Error setting value to 'GameMode' on 'RiotSharp.GameEndpoint.Game'.

**Comment by villam98** [comment]
I think, this could be the enum is missing, same as 'GetCurrentGame' #278 ticket, 3 month ago.

**Comment by BenFradet** [comment]
Are you using develop or the 2.5.1 nuget?

**Comment by villam98** [comment]
I'm using Visual Studio with the latest 2.5.1 nuget. What are you mean under "develop"?

**Comment by BenFradet** [comment]
There have been fixes merged in the develop branch but I haven't had time to publish a nuget containing those changes yet.

**Comment by villam98** [comment]
Ohh I see...so i have to wait for the nuget publish, or download from the github and import it. Right?

**Comment by BenFradet** [comment]
Unfortunately yes, I'll try to publish a 2.5.2 this week.

**Comment by BenFradet** [comment]
I just published it (sorry for the delay).

Could you check that 2.5.2 resolves your issue?

**Comment by BenFradet** [comment]
Closing, feel free to reopen if the problem persists.
