### ISSUE TITLE
StaticApi champion spells returns null

### ISSUE THREAD

**Issue by JobRapati** [BenFradet/RiotSharp#319]
When I try getting the champion spells from the static api it always returns null.
Code similar to mine in my problem:
`StaticRiotApi staticApi = StaticRiotApi.GetInstance("Key");`
`var spells = staticApi.GetChampion(region, championId).Spells;`

where key is my dev api key, region is a region variable that got already set and championId is a valid champion id.

**Comment by BenFradet** [comment]
Mmh weird, I'll have to investigate this one.

**Comment by BenFradet** [comment]
By default, the minimum champion data is retrieved.

If you want to access the spells for a champ, you should do:

```c#
var spells = staticApi.GetChampion(region, championId, ChampionData.spells).Spells;
```

You can have a look at [ChampionData](https://github.com/BenFradet/RiotSharp/blob/master/RiotSharp/StaticDataEndpoint/DataRequested.cs#L6-L27) to get a feel of what you can get from this endpoint.

**Comment by JobRapati** [comment]
Alright thanks for the help!

**Comment by BenFradet** [comment]
np, closing
