### ISSUE TITLE
Match & Matchlist End Point

### ISSUE THREAD

**Issue by jono-90** [BenFradet/RiotSharp#320]
Each API endpoint has it's own directory except for MatchEndPoint which contains both match and matchlist endpoint objects.

Should these two be separated? In other words, moving the matchlist stuff into it's own MatchListEndpoint directory.

It may clear up confusion between enums such as Queue and QueueType, and also the matchlist related enums can be moved from Misc into the new endpoint. 

Let me know what you think.

**Comment by BenFradet** [comment]
I do think it's a good idea. I think it's that way because of the overlap between the two endpoints but I agree that splitting them would make things clearer :+1: .

**Comment by jono-90** [comment]
OK makes sense. would there be another way to split them? otherwise feel free to close this :).

**Comment by BenFradet** [comment]
Have you tried splitting them? It'd be interesting to get a sense of what the overlap actually is.

**Comment by jono-90** [comment]
I had another look and almost all of it overlaps except for a few files/enums, so it's actually going to be a small grouping.

Here it is:
https://github.com/jono-90/RiotSharp/tree/develop/RiotSharp/MatchListEndPoint

can make a pull request if you still think it's a good idea.

**Comment by BenFradet** [comment]
I think it's worth opening a PR :+1:
