### ISSUE TITLE
Additional information: Error setting value to 'GameMode' on 'RiotSharp.GameEndpoint.Game'.

### ISSUE THREAD

**Issue by creepercats** [BenFradet/RiotSharp#322]
Hey i'm having an issue using the riotSharp nuget packacge. Im new to API programming in general but it seems like anytime i try to get something it returns me with an error. This error is for getting recent games. I might be using the package wrong and if i am please explain what im doing worng. Thanks! here is an image of the error / code https://gyazo.com/265ac24825791bdd441959bc3c6f5585

**Comment by BenFradet** [comment]
Hey, which version of the nuget are you using?

**Comment by creepercats** [comment]
RiotSharp 2.5.2 https://gyazo.com/e347825faaa93834a7df3be2adcfbd0b

**Comment by BenFradet** [comment]
Welp it seems a game mode is missing in RiotSharp.

I'd suggest trying the same request on https://developer.riotgames.com/api/methods and compare the returned game mode with what's in RiotSharp/Misc/GameMode.cs to see which one is missing.

Feel free to open a PR if you find it.

**Comment by creepercats** [comment]
Hey it seems i have a found a gamemode names "ASSASSINATE" that is not in your package Gamemodes. Here is a picture. https://gyazo.com/1abd2bde0545360099be661ba6f26bca

**Comment by BenFradet** [comment]
That seems to be it yes, feel free to open a PR :+1:

**Comment by creepercats** [comment]
How do i open a PR? Im new to all of this. Sorry :/

**Comment by BenFradet** [comment]
I'd suggest having a look at https://guides.github.com/activities/contributing-to-open-source/ especially the part about pull request :+1:.

**Comment by creepercats** [comment]
PR Sent

**Comment by creepercats** [comment]
Tested the code. And now it's throwing a different error concerning the SummonerBase.cs 

https://gyazo.com/fb3c9c4e4b33d5b07ca47c254a045d97
