### ISSUE TITLE
RiotSharp.StaticDataEndpoint.ChampionSpellStatic.Key is not consistent between champs

### ISSUE THREAD

**Issue by mmcelroy90** [BenFradet/RiotSharp#333]
RiotSharp.StaticDataEndpoint.ChampionSpellStatic.Key is not consistent between champs.

The example shows that the key should be AatroxQ, AatroxW, etc. However, that is only true for certain champs.

While some champions do follow that convention (Aatrox, Ivern).. others do not.
An example of one that doesn't work:
Amumu's key for his Q comes up as 'Bandagetoss' instead of 'AmumuQ'

I was looping through the spells for a selected champ and I was going to assign it to it's specific variable... however this code doesn't work when one of the problem champs (Amumu) are selected.

Code:
foreach(RiotSharp.StaticDataEndpoint.ChampionSpellStatic ability in champAbilitiesList)
                {
                    if (ability.Key.Equals(champion.Name + "Q"))
                    {
                        champion.QAbilityName = ability.Name;
                        champion.QAbilityDescription = ability.Description;
                    }
                    else if(ability.Key.Equals(champion.Name + "W"))
                    {
                        champion.WAbilityName = ability.Name;
                        champion.WAbilityDescription = ability.Description;
                    }
                    else if(ability.Key.Equals(champion.Name + "E"))
                    {
                        champion.EAbilityName = ability.Name;
                        champion.EAbilityDescription = ability.Description;
                    }
                    else if(ability.Key.Equals(champion.Name + "R"))
                    {
                        champion.RAbilityName = ability.Name;
                        champion.RAbilityDescription = ability.Description;
                    }
                }

Is it possible to get this fixed? If not, do you have a way of making my logic work so each ability is correctly aligned up with it's variable?

Thanks.

**Comment by BenFradet** [comment]
This is not an issue with RiotSharp but rather the API itself, I suggest you report your problem there https://developer.riotgames.com/.

**Comment by Heartfilia** [comment]
This is indeed an issue with Riot's API - but for OP, I believe the spells always come through in order.

Index 0 = Q
Index 1 = W
Index 2 = E
Index 3 = R
