### ISSUE TITLE
'Error setting value to 'Partype' on 'RiotSharp.StaticDataEndpoint.ChampionStatic'.'

### ISSUE THREAD

**Issue by Heartfilia** [BenFradet/RiotSharp#334]
Receiving the following error from Newtonsoft.Json.JsonSerializationException when trying to load StaticApi.GetChampions(Region.euw, ChampionData.all). Using anything other than .all seems to work okay.

: 'Error setting value to 'Partype' on 'RiotSharp.StaticDataEndpoint.ChampionStatic'.'
InnerException
NullReferenceException: Object reference not set to an instance of an object.

**Comment by BenFradet** [comment]
Which version are you using?

**Comment by Heartfilia** [comment]
2.5.3, Latest stable on Nuget - Shall I try -pre or from source?

**Comment by Heartfilia** [comment]
Just tried from source, can confirm working :)

**Comment by BenFradet** [comment]
Something must have gone wrong during the release. I'll try fixing it.
