### ISSUE TITLE
DotNet Core support

### ISSUE THREAD

**Issue by ddurschlag** [BenFradet/RiotSharp#335]
I ginned up something approximating dotnet core support at https://github.com/ddurschlag/RiotSharp/tree/dotnetcore .  Not sure if it's appropriate for pull request, since it overhauls the csproj files, and I don't know what, if anything, I broke support for. Certainly, there are plenty of tests that don't pass.

**Comment by BenFradet** [comment]
Please do open a PR!

tests are also failing on master because of 429s so this might not be related

**Comment by BenFradet** [comment]
closing this since there is already #332
