### ISSUE TITLE
Live Ranked Game data

### ISSUE THREAD

**Issue by ikazimirs** [BenFradet/RiotSharp#341]
Hi Is it possible to add section for pulling live game data?

**Comment by BenFradet** [comment]
Do you mean to the readme?

**Comment by ikazimirs** [comment]
Does your C# wrapper have a section for live games? as in the games you are in at the moment i cant seem to locate it

**Comment by BenFradet** [comment]
Yup, through [`GetCurrentGame`](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#L1168-L1194).

**Comment by ikazimirs** [comment]
I installed via PM would it be possible im on the wrong version as that funciton does not exist for me

**Comment by ikazimirs** [comment]
Woops never mind sorry im being an absolute bozo found it. was using it on summoner instead of on instance

**Comment by BenFradet** [comment]
No problem :+1:
