### ISSUE TITLE
List all possible issues from the Riot API v3

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#343]
https://discussion.developer.riotgames.com/articles/652/riot-games-api-v3.html

**Comment by MingweiSamuel** [comment]
They are removing batched calls? That could really decrease throughput

**Comment by BenFradet** [comment]
It seems so yeah :'(

**Comment by MingweiSamuel** [comment]
They have added per-endpoint rate limit functionality. Currently the limit is 2000req/sec for all endpoints, so it does not affect anything. In the future if the per-endpoint limit goes down or key rate limits go up (or if product key that has higher non-standard rate limits was used) it could be an issue. For now, not worth worrying about, but worth noting

(https://developer.riotgames.com/rate-limiting.html)

**Comment by BenFradet** [comment]
closing, since the change is happening today, problems will surface on their own
