### ISSUE TITLE
Region to platform in the endpoint URL

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#345]
API ref: https://discussion.developer.riotgames.com/articles/652/riot-games-api-v3.html

Code ref:
- https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RateLimitedRequester.cs#L25
- https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RateLimitedRequester.cs#L48
- etc

every occurrence of region needs to be platform according to this mapping https://developer.riotgames.com/regional-endpoints.html

**Comment by JanOuborny** [comment]
Addressed in #391. Closing.
