### ISSUE TITLE
Remove the stats endpoint

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#346]
Whether it's a deprecation or hard removal has to be figured out, cf https://discussion.developer.riotgames.com/articles/652/riot-games-api-v3.html

**Comment by toothlessG22** [comment]
Probably should just remove as after Riot shuts it down it will only Error.

**Comment by BenFradet** [comment]
yup agreed, I think we need to remove as much as we can

**Comment by BenFradet** [comment]
Fixed in #400
