### ISSUE TITLE
Move the champion API to V3

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#349]
API ref: https://developer.riotgames.com/api-methods/#champion-v3
Code ref: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#L185-L213

**Comment by msarsha** [comment]
Code ref is valid?

It points to the Match methods.

**Comment by BenFradet** [comment]
It wasn't, nicely spotted :+1: , I updated it.
