### ISSUE TITLE
Integrate the new Runes API

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#350]
API ref: https://developer.riotgames.com/api-methods/#runes-v3

I don't this has an equivalent in the current RiotSharp codebase.

**Comment by nickwilliamsnewby** [comment]
I would love to take a crack at this is anyone currently working on it?

**Comment by BenFradet** [comment]
@nickwilliamsnewby are you still working on it?

**Comment by oisindoherty** [comment]
I'm willing to work on this as well, considering we haven't heard a response from @nickwilliamsnewby in three weeks.

**Comment by nickwilliamsnewby** [comment]
That's fine with me sorry I've been absent, new job and house with no day care right now

Sent from my iPhone

On Jul 25, 2017, at 2:17 PM, Oisin Doherty <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm willing to work on this as well, considering we haven't heard a response from @nickwilliamsnewby<https://github.com/nickwilliamsnewby> in three weeks.

**Comment by JanOuborny** [comment]
@oisindoherty Don't forget to rebase onto `develop` when my PR is merged.

**Comment by oisindoherty** [comment]
Got it, thanks.

**Comment by BenFradet** [comment]
@nickwilliamsnewby that's no problem 👍

**Comment by Shidesu** [comment]
No news from @oisindoherty ? I could make a try if not.

**Comment by oisindoherty** [comment]
Sorry, got caught up in a few things. I have the changes on an old hard drive that I can get set up by the end of the day.
