### ISSUE TITLE
Move the tournament API to V3

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#353]
API ref: https://developer.riotgames.com/api-methods/#tournament-v3
Code ref: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/TournamentRiotApi.cs

**Comment by JanOuborny** [comment]
Can you assign me this issue? Because I need a tournament key it would be nice to have a reason for it before making a request at Riot.

**Comment by BenFradet** [comment]
I can't assign issues to people who don't have push access to the repo unfortunately 😞
