### ISSUE TITLE
Out of the box support for CultureInfo

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#357]
As far as I'm aware of, there is no out of the box support for converting the `CultureInfo` class into a `Language` enum. 
But since the only reason for the `Language` enum is to provide localization, why isn't there an out of the box support for the standard .NET localization class.
Therefore, it would be useful to provide an extension method `ToLanguage()` for the `CultureInfo` class.

The only downside of this solution would be that we need to reference `System.Globalization`.

**Comment by BenFradet** [comment]
Good idea!

However language is part of the list of enums that has to go in #307, so the `ToLanguage` extension method would return a `String`.

**Comment by CommanderJo** [comment]
I would like to take both tasks. However, I'm wondering if you want an input validation of the language string. If so, it would be smarter to don't change it to a string. Riot isn't very often adding a new language, so it won't  make a big maintenance problem.

**Comment by BenFradet** [comment]
True, I don't feel strongly about `Language` being an enum or not since it hasn't represented a huge maintenance burden.
