### ISSUE TITLE
Removing API method references from Tournament classes 

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#367]
Right, now the `Tournament` class and the `TournamentDetail` contain methods, like `CreateTournamentCode`, `static Get()` or `Update`, which are basically wrappers for the Tournament API endpoint.
If we try to enforce a clean SoC, we should remove these methods and replace them with something like this:

- `CreateTournamentCode(Tournament tournament, int count, ...)` (If we don't remove the `Tournament` class)
- `UpdateTournamentCodeDetail(TournamentCodeDetail detail)`
- Remove `static Get `methods entirely 

As far as the `Tournament` class goes, I would remove it completely and just return an int.

**Comment by BenFradet** [comment]
That makes sense to me :+1:
