### ISSUE TITLE
Team Endpoints are tested that no longer exist in Riot's API

### ISSUE THREAD

**Issue by toothlessG22** [BenFradet/RiotSharp#370]
These endpoints have been removed by Riot and cause 403 errors in their tests. They should at least be removed from the tests.

 [LeagueByTeamUrl](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#38), [TeamRootUrl](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#42), [TeamBySummonerUrl](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#43)

All of these endpoints have been removed per [Riot's removal notice.](https://discussion.developer.riotgames.com/articles/74/the-deprecation-of-ranked-teams-by-early-december.html)

**Comment by BenFradet** [comment]
Skipped right through that one, good catch.
