### ISSUE TITLE
Inconsistency in Definition of Test Values

### ISSUE THREAD

**Issue by toothlessG22** [BenFradet/RiotSharp#379]
The definitions of test values are strewn across the test files. Some are defined in test functions. Some are defined in App.config. Some are defined at the top of the test files.

Moving all of the definitions into App.config would make debugging easier.

**Comment by JanOuborny** [comment]
I would even extend this issue and move all definitions of the test values into a `TestBase` class for every endpoint.

**Comment by toothlessG22** [comment]
So for each test class, e.g. RiotApiTest, have a class called RiotApiTestBase?

How would things that are in each test be handled? For example, the API key is the same across all tests and trying to find and fill in all definitions of it would be tedious. Could have a CommonTestBase for values that are needed by multiple tests.

**Comment by JanOuborny** [comment]
It wouldn't be tedious if you load the api key once from the `ConfigurationManager` in each test base and then reference it as a variable in the tests. And yes you can have a `CommonTestBase` from which every other `TestBase` can inherit that would make it even easier.
