### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by florinciubotariu** [BenFradet/RiotSharp#381]
Wouldn't it be a good idea implement dependency injection using the IoC principle?  This with a mocking framework would help us when unit testing.
This pull request https://github.com/BenFradet/RiotSharp/pull/253 tried to achieve that but no more actions were made in that direction.

**Comment by BenFradet** [comment]
Yup, apparently she/he deleted her/his account though.

**Comment by JanOuborny** [comment]
If you look into my latest pull request #380, I used #253 as a base and rewrote the requester with this point in mind.

**Comment by florinciubotariu** [comment]
I've worked only with [SimpleInjector](https://simpleinjector.org/index.html).
Any ideas on how to achieve this since we don't have an entry point to register the container?

**Comment by JanOuborny** [comment]
I think we shouldn't implement the dependency injection by ourselves. Instead we should offer the required constructors. The users should configure their containers by themselves.
What we could provide is an extension method for the ASP.NET Core DI container and what we should provide, is a parameterless constructor, in which the api class can supply itself with the instances of the required services.

**Comment by JanOuborny** [comment]
Is it possible to create a new NuGet package, something like `RiotSharp.AspNetCore`, for the `IServiceCollection` extension, which include the DI setup? This would avoid any unnecessary dependencies for the main package.

**Comment by BenFradet** [comment]
That's something worth investigating I think.

Would RiotSharp (the main pkg) depend on this or would it live by itself?

**Comment by JanOuborny** [comment]
It would depend on RiotSharp. Therefore, it wouldn't live by itself, but RiotSharp would be independent.

**Comment by BenFradet** [comment]
works for me :+1:
