### ISSUE TITLE
Uniform unit test naming

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#385]
Right now the naming of the unit tests is rather random. I suggest that we use this naming convention:

`MethodName_StateUnderTest_ExpectedBehavior()`

**Comment by entvex** [comment]
Hello @BenFradet and @JanOuborny 
Is this still up for grabs ?

**Comment by BenFradet** [comment]
yes :+1:

**Comment by entvex** [comment]
Hello Ben,
Please see https://github.com/BenFradet/RiotSharp/pull/673
I hope you have an awesome day :)

**Comment by entvex** [comment]
As the code as been accepted, I think we can close this issue 👍
