### ISSUE TITLE
How to get users rank/league?

### ISSUE THREAD

**Issue by MCUnderground** [BenFradet/RiotSharp#388]
I am still learning how to c#, and i dont get how to get current rank/league of user.
Can anyone help?

**Comment by BenFradet** [comment]
To get the leagues for a summoner:

```c#
var api = RiotApi.GetInstance(API_KEY);
var summoner = api.GetSummoner(RiotSharp.Region.na, summonerId);
var leagues = summoner.GetLeagues();
```

**Comment by MCUnderground** [comment]
I got that, still dont understand how to get Tier i tried GetEnumerator, but i dont think thats it.

**Comment by BenFradet** [comment]
```c#
foreach (var league in leagues)
{
  Console.WriteLine(league.Tier);
}
```

**Comment by MCUnderground** [comment]
Oh that, thank you. You can close this :)

**Comment by BenFradet** [comment]
No problem.
