### ISSUE TITLE
New Game mode (Darkstar)

### ISSUE THREAD

**Issue by briedrice** [BenFradet/RiotSharp#390]
There was a new game mode and map added, and is causing my match history code to error out. Is there a work around or do I just need to update my version of riot sharp?

**Comment by BenFradet** [comment]
It's always a good idea to update, if that doesn't work it might not be in RiotSharp altogether so we'll have to add it.

**Comment by briedrice** [comment]
Just made the update. Seems like it is still missing the new game mode in the GameMode Enum, It probably won't matter too much unless they bring it back

**Comment by BenFradet** [comment]
If you find out which GameMode it is you can always open a pr adding it and then build riotsharp from source until they remove the match history endpoint.

**Comment by JanOuborny** [comment]
It will mostlikely come back as part of the rotating game modes. Therefore I would highly recommend adding it to the `GameMode` enum.

**Comment by JanOuborny** [comment]
@BenFradet Can you add the Darkstar changes to the maintenance release?

**Comment by BenFradet** [comment]
@JanOuborny yup, I should be able to release it today.

**Comment by BenFradet** [comment]
I published 2.5.6 which should solve this, keep us updated

**Comment by BenFradet** [comment]
closing as this should be solved
