### ISSUE TITLE
 Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by briedrice** [BenFradet/RiotSharp#394]
I keep getting the error below when trying to retrieve the summoner name from the ID. 

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'status', line 1, position 12.

I have not seen this type of error, and was wondering if anyone is familiar with it

**Comment by BenFradet** [comment]
If you don't mind can you paste the exact call you're making and the ID?

**Comment by briedrice** [comment]
var players = game.FellowPlayers;
var team = new List<PlayerInfo>();

                foreach (var player in players)
                {

                    var theTeam = new PlayerInfo();
                    var champ = champions.Where(x => x.Id == player.ChampionId).First();
                    var image = champ.Image.Full;
                    var summonerId = player.SummonerId;

                    **theTeam.Summmoner = myApi.GetSummonerName(Region.na, player.SummonerId).Name;**
                    theTeam.championImage = ConvertToImage("champion", image, version);
                    theTeam.championName = champ.Name;
                    theTeam.TeamId = player.TeamId;

                    team.Add(theTeam);
                }

                theGame.Players = team;

**Comment by briedrice** [comment]
That is the original code. I ended up removing it from the loop to see which ID caused the problem,  but it seems the error occurs on any third call to "GetSummonerName".

ex: If I execute the code below, the 3rd Summoner Always ends up an error no matter what the ID.

theGame.Summoner0 = myApi.GetSummonerName(Region.na, theGame.Players[0].Summmoner).Name;
theGame.Summoner2= myApi.GetSummonerName(Region.na, theGame.Players[2].Summmoner).Name;
theGame.Summoner3= myApi.GetSummonerName(Region.na, theGame.Players[3].Summmoner).Name;

**Comment by briedrice** [comment]
It seems When I take it out of the loop and and call those three by Id they work just fine. any ideas?

**Comment by BenFradet** [comment]
My guess is Riot is throttling and you're getting incorrect 429s.

If you want to confirm you might debug the responses that RiotSharp is getting.

**Comment by JanOuborny** [comment]
@BenFradet  I think we should merge PR #382 into master and publish it as a maintainance patch to avoid confusion. Furthermore I would add a default case for any error, which isn't caught by the different cases, to avoid any further processing after the request failed.

**Comment by BenFradet** [comment]
Sounds like a plan, I'll try to cherry-pick this fix and make a release
tomorrow.

**Comment by JanOuborny** [comment]
Don't forget to add the default case. I think it is not included in #382.

**Comment by briedrice** [comment]
Since it sounds like a Rate limit problem. Is there a work around or do I need to get a Production Api

**Comment by BenFradet** [comment]
I published 2.5.6 which should fix this, keep us updated.
