### ISSUE TITLE
Debugging rate limiting?

### ISSUE THREAD

**Issue by mattmast** [BenFradet/RiotSharp#406]
I'm getting myself ramped up to help out and looking at moving the Mastery Pages to V3 (is there an open issue for this?).  Since V3 doesn't support batch, I'm just creating a request per summoner ID at the new V3 endpoint.  The unit test requests masteries for 11 summoners.   

However, I keep getting rate limited.  Other unit tests fail due to rate limiting as well, so it's not just isolated to the new code.  I change ```RateLimiter.TenSeconds``` to 11 seconds and my test and others pass.  I've stared at this for a couple days now and I'm not seeing the issue other than it seems timing related.

Changing ```RateLimiter.TenSeconds``` to 11 seems like a hack, so any advice on debugging this?

**Comment by JanOuborny** [comment]
The unit tests require a refactoring. Make an unit test do only one call except it's a special test, which tests rate limit or requires multiple calls. Otherwise when refactoring, please use the new unit test naming #385.

For the issue with the rate limiter I can't give you more information right now.

**Comment by mattmast** [comment]
Let me ask this.  Are all the unit tests expected to pass?

**Comment by JanOuborny** [comment]
Technically the should. In practice some might fail due to your rate limit of your develop key. For your development is only important that your specific tests pass.

**Comment by toothlessG22** [comment]
I just rerun tests that failed because of rate limiting (429 Error).

**Comment by BenFradet** [comment]
There are also tests that are always failing which should be marked with `[Ignore]`, we should delete or fix them.

**Comment by mattmast** [comment]
I see the workflow now.  This can be closed.
