### ISSUE TITLE
Get profile icons?

### ISSUE THREAD

**Issue by VikkeDD** [BenFradet/RiotSharp#422]
Hello, im using your proyect to do a WPF app, but i cant find GetProfileIcons(). Im missing something? Wrong version? Thank you a lot for the incredible plugin anyways

**Comment by VikkeDD** [comment]
Im using the v2.5.6 version, so maybe is not implemented yet. Cant find it on the clone version neither, so ill have to wait. Thanks for that fast reply

**Comment by JanOuborny** [comment]
Here you go. Just rename it to `RiotSharp.3.0.0.nupkg` and place it in your local NuGet feed.
[RiotSharp.3.0.0.zip](https://github.com/BenFradet/RiotSharp/files/1081469/RiotSharp.3.0.0.zip)

**Comment by VikkeDD** [comment]
It works! 

http://prntscr.com/fklojc

Now i have to cache all that images. Thanks a lot, really!

**Comment by JanOuborny** [comment]
You're welcome. Good luck with your project 👍

**Comment by JanOuborny** [comment]
@VikkeDD Don't forget to delete this package and to update to the real 3.0.0 version when it's out.

**Comment by VikkeDD** [comment]
@JanOuborny Hello again, Riot changed endpoint from match and matchlist but i cant get updated nugget package, can you tell me how to add Github proyect to mine or do a nugget package? Sry for my english, and thx for all the help

**Comment by JanOuborny** [comment]
@VikkeDD  Here you go #445
