### ISSUE TITLE
GameSubType missing

### ISSUE THREAD

**Issue by xRow3** [BenFradet/RiotSharp#424]
Dark Star: Singularity is missing from the enum of GameSubTypes, making impossible to set properties of that in matches played in Singularity.

**Comment by JanOuborny** [comment]
Good catch 👍  let me fix that

**Comment by xRow3** [comment]
Thank you very much, will it be pushed to NuGet or will I have to download the library from here and install VS2017?

**Comment by JanOuborny** [comment]
@BenFradet will probably push a maintenance build tonight. If not I can send you a NuGet package for your local feed, but that would be also later tonight.

**Comment by BenFradet** [comment]
Unfortunately I won't be able to build a nuget for the next 10 days :(

**Comment by JanOuborny** [comment]
@xRow3 Then here is your latest develop build NuGet package. It's already version 3.0.0. Therefore keep in mind you will need to migrate some code, but you would need to do it later anyway.

[RiotSharp.3.0.0-beta.zip](https://github.com/BenFradet/RiotSharp/files/1082813/RiotSharp.3.0.0-beta.zip)

Don't forget to rename it back to `RiotSharp.3.0.0-beta.nupkg`

**Comment by xRow3** [comment]
Thank you very much for the quick work!

**Comment by JanOuborny** [comment]
RiotSharp v3 targets .NET Standard 1.3, because of this .NET 4.5.x isn't supported anymore. See [this matrix ](https://docs.microsoft.com/en-us/dotnet/standard/library#net-platforms-support)for a list of supported platforms.
