### ISSUE TITLE
Getting free to play champs

### ISSUE THREAD

**Issue by StebX** [BenFradet/RiotSharp#428]
I did it with api not static api and it works, the problem is I dont know how to find the freetoplay champs
with the static api because there's no .FreeToPlay.

Code Below: 
```
var freechamps = api.GetChampions(region, true);
foreach (var champ in freechamps)
{
     if (champ.FreeToPlay)
     {
          freechamps_txt.Text = freechamps_txt.Text + " " + champ.Id;
     }
}
```

The code below works to get all the champ name but i dont know how to find the freetoplay champs.

```
var champions = staticApi.GetChampions(region, ChampionData.all).Champions.Values;
foreach (var champ in champions)
{
      freechamps_txt.Text = freechamps_txt.Text + " " + champ.Name;
}
```

**Comment by MingweiSamuel** [comment]
The free champions are not static data -- they change every week. You can pull the free champion ids first using the normal api then use the static api to get additional data on those champions.

**Comment by StebX** [comment]
Fixed it =D but the output is this  Corki Fizz Galio Kalista Kayle Kha'Zix Morgana Nautilus Orianna Rengar Riven Yasuo it should be 10 champs only .

For readers here is my code:
`
 var freechamps = api.GetChampions(region, true);

            foreach (var champ in freechamps)
            {
                if (champ.FreeToPlay)
                {
                    int id = unchecked((int)champ.Id);
                    var champsconverted = staticApi.GetChampion(region, id, ChampionData.all);
                    freechamps_txt.Text = freechamps_txt.Text + " " + champsconverted.Name;
                }
            }
`

**Comment by BenFradet** [comment]
Yup we've had this issue forever in the tests: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp.Test/RiotApiTest.cs#L126-L152

**Comment by StebX** [comment]
Also, I'm getting this error getting player's win lose stat.
[http://prntscr.com/fp90oj](url)

Code:
`
 var summaries = summoner.GetStatsSummaries();
            var soloqSummary = summaries.Where(summary => summary.PlayerStatSummaryType == RiotSharp.StatsEndpoint.Enums.PlayerStatsSummaryType.AramUnranked5x5).FirstOrDefault();
            var wins = soloqSummary.Wins;
            var losses = soloqSummary.Losses;
            MessageBox.Show(wins.ToString() + losses.ToString());
`

**Comment by BenFradet** [comment]
The stats endpoint has been removed by riot and us in #400

**Comment by StebX** [comment]
Also =D, can you get participant's item from getcurrentgame ?

**Comment by JanOuborny** [comment]
I don't think you can, but you could do this after the game has ended.

**Comment by msarsha** [comment]
@StebX Didn't riot changed free champions number to 12 ? It was 10 in the past (I might be outdated though)

**Comment by JanOuborny** [comment]
@msarsha  Looking at the [latest rotation](http://euw.leagueoflegends.com/en/news/champions-skins/free-rotation/new-free-champion-rotation-ahri-darius-jinx-and-more), it seems like it is still 10. At least for EUW. Might be different for other regions.

**Comment by BenFradet** [comment]
closing since I think the original question was answered.
