### ISSUE TITLE
Starting to contribute

### ISSUE THREAD

**Issue by VitorCioletti** [BenFradet/RiotSharp#429]
I am new in participating in projects like these, so I have questions about how to do it. Can someone give me a hint on where and how to start doing it? Anything would be helpful. 
I already know C# and developed a simple application using RIOT's API, so I already know the main concepts of it. My main problem is that I have no idea on how to be helpful to this project. I would really like to be.
Where do I Start?

Obs: sry if this is not the adequated place to ask questions.

Thank you :)

**Comment by BenFradet** [comment]
You can pick an open issue from https://github.com/BenFradet/RiotSharp/issues, adding a comment saying that you've started working on it.

Once you have a fix you can open a pull request and we'll be happy to merge it.

**Comment by VitorCioletti** [comment]
Oh. Nice. I will start doing something right now :).
Thank you, Ben.
