### ISSUE TITLE
Move the match API to V3

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#433]
API ref: https://developer.riotgames.com/api-methods/#match-v3
Code ref: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#L369-L481

**Comment by dgraney** [comment]
Any update on the progress made here?

Might try playing with this, if not.

**Comment by JanOuborny** [comment]
I've done quit a bit. Just use my [match-api](https://github.com/BenFradet/RiotSharp/tree/match-api) branch as the starting point and create a pull request into it, when you are done.

**Comment by BenFradet** [comment]
Last ticket for 3.0.0!

**Comment by Shidesu** [comment]
If @dgraney can't do it, I could finish this soon.

**Comment by JanOuborny** [comment]
@dgraney You can do it if @dgraney doesn't respond until tomorrow. But don't forget to rebase onto my branch.
