### ISSUE TITLE
Remotename couldn't be resolved (euw.api.pvp.net)

### ISSUE THREAD

**Issue by ChristianFreak** [BenFradet/RiotSharp#445]
So I followed the little code snippets along and tried to print some information about a player.
My program crashes at the GetSummoner() Method (system.aggregateexception)
For more detail here is my code: https://hastebin.com/qokiraduki.cs

I tried it also with a simpler one on my other computer and also got the 2 excpetions.

Edit: I think it needs to be euw1.api.riotgames.com

**Comment by BenFradet** [comment]
the endpoint changed from api.pvp.net to api.riotgames.com, you can try building from source in the meantime

**Comment by JanOuborny** [comment]
You can build your own NuGet package of the latest version with this command:
`msbuild /t:pack /p:Configuration=Release`

**Comment by ChristianFreak** [comment]
So I did these steps:
Opened up dev console->navigated to the folder I extracted from the zip file (dev branch)->typed the command to build the nuget package->1 Error 255 Warnings (Couldn't find pack)

I'm sorry if I miss understood something I never did something like this.
In advance it would be a big help for everyone to setup a Discord Server for helping people

**Comment by JanOuborny** [comment]
Can you show me the exact path from which you called the command?

**Comment by ChristianFreak** [comment]
C:\Users\Christian\Desktop\mods\RiotSharp-develop\RiotSharp-develop

**Comment by JanOuborny** [comment]
You have to go into the folder where the `RiotSharp.csproj` is.

**Comment by ChristianFreak** [comment]
So I have a Debug and a Release folder. I guess I need to pick the files from the Release folder right?

**Comment by JanOuborny** [comment]
Yep, there should be a .nupgk Take it and add to your local NuGet source.

**Comment by ChristianFreak** [comment]
Alright so far it's working fine without any errors. Thank you for your help!

**Comment by VikkeDD** [comment]
I cant really find where is the Dev console, googled it and it seems that my Visual Studio 2016 doesn't have the msbuild command / im doing something wrong. Sry for being a newbie :/ Any help?

![screenshot_589](https://user-images.githubusercontent.com/15320648/28887904-1f092ea2-77bf-11e7-8e20-9b81af4261a0.png)

**Comment by JanOuborny** [comment]
My spanish isn't so good, but judging from your error, you are not using VS 2017 to build the project. However, this is required for the new project format.

**Comment by VikkeDD** [comment]
@JanOuborny Just updated Visual Studio to 2017 version, but now i get like 7k errors wheb msbuild 
![screenshot_15](https://user-images.githubusercontent.com/15320648/29114081-63e5e6f8-7cf3-11e7-9b6c-091c27423e79.png)

**Comment by JanOuborny** [comment]
Open it in VS 2017 and restore all packages. This should make all errors disappear. Then retry the command.
