### ISSUE TITLE
Change parameter in GetChampion to long data type

### ISSUE THREAD

**Issue by ChristianFreak** [BenFradet/RiotSharp#446]
When you cast the Champion.Id it returns a long data type but in the GetChampion function it requires a int data type. Btw: I know you can cast it to an int.

**Comment by JanOuborny** [comment]
Actually, there are also some inconsistencies at Riot's endpoint. If you look at the [match endpoint](https://developer.riotgames.com/api-methods/#match-v3/GET_getMatch), champion ids are returned as `int`s. However, in the [champion mastery endpoint](https://developer.riotgames.com/api-methods/#champion-mastery-v3/GET_getChampionMastery) the champion id for filtering is required as an `long`. 

But can you tell me, which champion ids are you reffering exactly?

**Comment by ChristianFreak** [comment]
I just went through all Champions with a foreach loop

**Comment by ChristianFreak** [comment]
Is there currently a way to get the Champion name, because I didn't find it on the riot documentation.

**Comment by JanOuborny** [comment]
I suppose you are talking about the static endpoint, but there the champion id is an `int`. At least as a parameter in `GetChampion` and the class `ChampionStatic`.

You can get the champion name from the `ChampionStatic` class.

**Comment by ChristianFreak** [comment]
Alright, now everything seems clear to me!
