### ISSUE TITLE
Champion Tags Null Error

### ISSUE THREAD

**Issue by ChristianFreak** [BenFradet/RiotSharp#447]
So when I try this line of code:
`foreach(var Tag in Champion.Value.Tags)`
`{`
`...`
`}`

the program throws at `Champion.Value.Tags` with an null reference error. (Champion is not null).

Edit: Skins and RecommendedItems too.

**Comment by JanOuborny** [comment]
Have you included the required data in your request?

**Comment by ChristianFreak** [comment]
I made a request for all champions with the static api and then I went through them to get their tags

**Comment by BenFradet** [comment]
What did you use for the `championData` argument https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticRiotApi.cs#L134 ?

**Comment by ChristianFreak** [comment]
Ah I see it's an optional paramater. I left it blank. Thank you guys for your help again!

**Comment by BenFradet** [comment]
no problem :+1:
