### ISSUE TITLE
Move the league API to V3

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#454]
API ref: https://developer.riotgames.com/api-methods/#league-v3
Code ref:
  - https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#L303-L417
  - https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/SummonerEndpoint/SummonerBase.cs#L140-L192

**Comment by Shidesu** [comment]
Hi, I would like to help, but I'm quite unsure on the modification that should be done here.
Looking through the code I thought the modifications had to be done around the constants but you highlighted  other lines. So I guess that I'm fully wrong :/

**Comment by BenFradet** [comment]
Unfortunately, not only the constants have to be modified.

AFAICT:

- they removed the endpoint where you could retrieve the leagues of multiple summoners in one call so [those two methods](https://s3-eu-west-1.amazonaws.com/sp-com-lifecake-658155941202-10-iglu-schemas) need to take only one `summonerId`
- leagues / entire leagues have been renamed to leagues / positions so we need to reflect that in the name of the methods

and I think that's it

**Comment by Shidesu** [comment]
Hum yeah I see.
(your link is just sending me to a raw XML file [or maybe chrome is just stupid])
I will try to do update this.
I'm quite new, so I'm not sure of how I'm supposed to do that.
But for the moment I cloned the development branch and so I will work on it.

**Comment by BenFradet** [comment]
woops it was the wrong link, updated

**Comment by Shidesu** [comment]
I updated the link for RecentGames, I checked the json result (which is not null), but every LINQ method is not working -> null exception. Can't find out the source of the error.

**Comment by Shidesu** [comment]
Was wondering, because it's now only One summonerId, do we keep a Dictionnary or just return a List of the Leagues ?

**Comment by BenFradet** [comment]
Yup no need for the dict 👍

**Comment by Shidesu** [comment]
-> I'm gonna fix this (or trying too) but the Json model for the old Entire Leagues is not fully compatible with the LeaguePositions (some names modifications into it)

**Comment by Shidesu** [comment]
Guys little 'issue' : 
LeagueEntry is pretty muche the same (in terms of Json keys / values) than the League Position. But, in League Position we have a queueType which is not present in LeagueEntry. So -> i create a brand new class LeaguePosition ? Inheriting League Entry ? :/ I'm waiting for your decision ^^

**Comment by BenFradet** [comment]
You can add it to the existing one while renaming it to `LeaguePosition`  👍

**Comment by Shidesu** [comment]
The code is ready i think :D 
At least ready for verifications, I'm pretty unsue on how to send it (used git for private projects so never had to pull request / fork or i don't know what)

**Comment by Shidesu** [comment]
I made a Pull Request #465 
I hope the code is okay.

**Comment by Shidesu** [comment]
I made a Pull Request #465 to fix this issue (#454)
I hope the code is okay.
