### ISSUE TITLE
League and matches fail

### ISSUE THREAD

**Issue by VikkeDD** [BenFradet/RiotSharp#455]
When im using dynamicAPI.GetLeagues() this happens every time 

403, Forbidden  
 en RiotSharp.Http.RequesterBase.HandleRequestFailure(HttpStatusCode statusCode)
 en RiotSharp.Http.RequesterBase.Get(HttpRequestMessage request)
 en RiotSharp.Http.RateLimitedRequester.CreateGetRequest(String relativeUrl, Region region, List`1 addedArguments, Boolean useHttps)
 en RiotSharp.RiotApi.GetRecentGames(Region region, Int64 summonerId)
 en League_of_legends_helper_v2.UserWindow.loadDataWindow()

**Comment by BenFradet** [comment]
This is because of #454

**Comment by VikkeDD** [comment]
Okey, so just wait until the update right? Im having a lot of trouble with my graduate work, sorry for all the posts

**Comment by BenFradet** [comment]
We're waiting for a few implementations before releasing 3.0.0 (#350, #351, #433 and #454 mostly)

**Comment by JanOuborny** [comment]
@VikkeDD Are you using RiotSharp for your graduation work?

**Comment by VikkeDD** [comment]
@JanOuborny Yes, as a support for my WPF desktop application

**Comment by Shidesu** [comment]
With #465 you should be able to get the Leagues soon.

**Comment by JanOuborny** [comment]
See #456 and #445 for more information if you want the latest build. Closing, feel free to reopen it if you have any questions.
