### ISSUE TITLE
Fresh install of API not pulling in the latest version

### ISSUE THREAD

**Issue by ikazimirs** [BenFradet/RiotSharp#457]
PM> Install-Package RiotSharp and GetSummoner throws an error. i see other comments where that method is depriciated and should be GetSummnerByName but it does not exist on the RiotSharp library

**Comment by BenFradet** [comment]
We're waiting for a few implementations before releasing 3.0.0 (#350, #351, #433 and #454 mostly)

You'll have to build from source in the meantime

**Comment by ikazimirs** [comment]
The build from source fails to load the RiotSharp project :( 

THe default XML namespace of the project must be in the MSBuild XML namespace.

**Comment by ikazimirs** [comment]
never mind - project is not compatible with VS2015 needs to be run on VS 2017

**Comment by JanOuborny** [comment]
Closing, feel free to reopen it if you have any questions.
