### ISSUE TITLE
Error on RecentGames() (from a summoner)

### ISSUE THREAD

**Issue by Shidesu** [BenFradet/RiotSharp#464]
While testing my updates to the Summoner Base.cs I'm having an issue.
The api send the data (i checked with breakpoints) , it looks like the deserialization is failling. 
Did not have time to dive into the deserialization but looks like it's no more working with the new json send by RIOT.

**Comment by JanOuborny** [comment]
Then you have to manually compare the models with the received JSON. I know it's tedious work, but there is no other way to migrate it.

**Comment by BenFradet** [comment]
This is part of #433

**Comment by JanOuborny** [comment]
And I think we are abandoning the summoner base concept, because it's badly maintainabe. Is this right @BenFradet?

**Comment by Shidesu** [comment]
So no need to update the GetLeagues from Summoner Base ?

**Comment by JanOuborny** [comment]
Yes, but you could help updating the match endpoint. See #433

**Comment by Shidesu** [comment]
I thought dgraney was doing this but yeah I could do this if needed.

**Comment by JanOuborny** [comment]
Then pick an other open issue.

**Comment by BenFradet** [comment]
>And I think we are abandoning the summoner base concept, because it's badly maintainabe. Is this right @BenFradet?

yup 👍
