### ISSUE TITLE
Loose coupling of RiotApi 

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#468]
From a maintenance and DI view, it makes sense to split the `RiotApi` in to different endpoints, which are then combined back together in the `RiotApi` class.

I propose following solution architecture:

* `RiotSharp.Endpoints.Interfaces`
  - `ISpectatorEndpoint`
  - `IRunesEndpoint`
  - `...`
* `RiotSharp.Endpoints`
    - `SpectatorEndpoint`
    - `RunesEndpoint`
    - `...`

In the `RiotApi` class the endpoints would be referenced like this:
``` c#
private ISpectatorEndpoint spectatorEndpoint = new SpectatorEndpoint(...);
public ISpectatorEndpoint Spectator => spectatorEndpoint;
```

Consumption of the endpoints would look like this:
``` c#
var api = RiotApi.GetInstance();
api.Spectator.GetCurrentGame(region, id);
```

**Comment by Shidesu** [comment]
For 3.1 i think :')
It will be nice and easier to maintain -> but a bit long to put in place.

**Comment by JanOuborny** [comment]
That's not really that hard. I would say in two to three hours it's done.

**Comment by BenFradet** [comment]
yup I think the most urgent stuff is to support the v3 api, this is a bit longer term 👍
