### ISSUE TITLE
Replace string.Format() with string interpolation

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#469]

**Comment by JanOuborny** [comment]
Unfortunately, this doesn't work with string variables 😞 But in some cases it is still possible, like [here](See #456 and #445 for more information. Closing, feel free to reopen it if you have any questions.).

**Comment by maferland** [comment]
Mind if I do it ?

**Comment by JanOuborny** [comment]
Of course not. Feel free to grab it.

**Comment by maferland** [comment]
I fixed every string.Format that were not on var. #474
