### ISSUE TITLE
Incompatible with dotnet core 2?

### ISSUE THREAD

**Issue by ddurschlag** [BenFradet/RiotSharp#482]
Adding the package to an empty console project gives a series of warnings about using dotnetframework 4.6.1 instead of dotnet core 2.0, then restore doesn't seem to work. Has this been tested working? Are there other steps? The patch to target .net standard 1.3 was supposed to make this possible, yes/no?

**Comment by JanOuborny** [comment]
The patch targeting .NET Standard 1.3 is not published, yet.

**Comment by BenFradet** [comment]
I just published 3.0.0 targeting dotnet core 2.0, closing
