### ISSUE TITLE
Riot API v3

### ISSUE THREAD

**Issue by 4nandou** [BenFradet/RiotSharp#486]
Hi, When do you think you will complete the port to V3 API? V1 and V2 APIs have been already deprecated. Thanks for any information. I'm mostly interested in match & tournaments APIs.

**Comment by BenFradet** [comment]
We're only waiting on #473 👍

**Comment by BenFradet** [comment]
I just published 3.0.0 :shipit:

**Comment by 4nandou** [comment]
Thanks a lot!
