### ISSUE TITLE
NuGet v3.0.0 No target specified

### ISSUE THREAD

**Issue by Talha-T** [BenFradet/RiotSharp#491]
`'RiotSharp 3.0.0' does not target '.NETFramework,Version=v4.5.2'`

**Comment by BenFradet** [comment]
yes we moved to dotnet core for 3.0.0

**Comment by 4nandou** [comment]
Shouldn't it target .Net Standard instead so that both .NET core 2 and .NET 4.6.1 could use the package?

**Comment by BenFradet** [comment]
my bad yes it targets .net standard 2.0

**Comment by Talha-T** [comment]
I get the same result with .NET 4.7, and 4.6.1

**Comment by JanOuborny** [comment]
Fixed with release of version 3.0.1. Closing.
