### ISSUE TITLE
Add third-party-code-v3 Endpoint

### ISSUE THREAD

**Issue by jwrichard** [BenFradet/RiotSharp#500]
Riot added a new endpoint used for 3rd parties to verify a summoner. Used to fix the old "Change your rune page name to xyz to verify".

Blog Post: https://discussion.developer.riotgames.com/questions/4269/verification-system.html
API Doc: https://developer.riotgames.com/api-methods/#third-party-code-v3/GET_getThirdPartyCodeBySummonerId

**Comment by BenFradet** [comment]
Good idea 👍

**Comment by jwrichard** [comment]
@BenFradet @Oucema90 Thank you 🙏
