### ISSUE TITLE
Change the language

### ISSUE THREAD

**Issue by Namysh** [BenFradet/RiotSharp#503]
Hello i'm french and I use this package for improve my knowledge in programation, I am a real beginner in programation. This package take the informations in english but i need to have those informations in french.
**For example for serialize champions data this link is used :**
 http://ddragon.leagueoflegends.com/cdn/6.24.1/data/en_US/champion.json 

**but i want french informations then I need to serialize data with this link  :**
http://ddragon.leagueoflegends.com/cdn/6.24.1/data/fr_FR/champion.json

My question is here, how change the link where the informations are serialized ? 

I hope you understand me, my english is not perfect as you can see

**Comment by BenFradet** [comment]
Hello, for most of the static calls you can specify a `Language` like [here](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticRiotApi.cs#L149):

```c#
var champions = staticApi.GetChampions(Region.euw, ChampionData.all, Language.fr_FR).Champions.Values;
foreach (var champion in champions)
{
    Console.WriteLine(champ.Name);
    Console.WriteLine(champ.Lore);
}
```

**Comment by Namysh** [comment]
Oh ok, thank you ^^
