### ISSUE TITLE
League-v3 getAllLeaguesForSummoner endpoint deprecated

### ISSUE THREAD

**Issue by jwrichard** [BenFradet/RiotSharp#504]
> The league-v3 getAllLeaguesForSummoner endpoint will be deprecated on Wednesday, January 10th, 2018. Please use getLeagueById as a replacement for this endpoint. Though we plan to deprecate the endpoint around noon Pacific time, we suggest having a solution in place at least 12 hours in advance that is ready to swap over as soon as the endpoint is removed.
> 
> For the most up-to-date information regarding changes to the Riot Games API, we recommend following our Twitter and checking for new forum announcements.
> 
> The Riot Games API Team

**Comment by JanOuborny** [comment]
Ref: https://developer.riotgames.com/api-methods/#league-v3/GET_getAllLeaguesForSummoner
