### ISSUE TITLE
Remove synchronous methods

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#511]
Given #510, it's now possible to safely call `api.MethodAsync().Result`.

As a result, we can get rid of the synchronous methods.

**Comment by Kirides** [comment]
Created a fork with the changes from #510 where i removed all the synchronous code (that i saw).

See: https://github.com/Kirides/RiotSharp/commit/7024ce5083c43791d9662e745730ca616e470b82

**Comment by BenFradet** [comment]
Nice 👍 , feel free to open a PR once we merge #510
