### ISSUE TITLE
GetRecentMatches, GetLeagues throws error

### ISSUE THREAD

**Issue by i3dprogrammer** [BenFradet/RiotSharp#519]
**RiotSharp v3.0.1 NuGet package**

```c#
var summoner = await _api.GetSummonerByNameAsync(RiotSharp.Misc.Region.eune, summonerName);
```

-  Using GetRecentMatches method

```c#
var matches = await _api.GetRecentMatchesAsync(RiotSharp.Misc.Region.eune, summoner.AccountId);
```

throws error

> Error setting value to 'Season' on 'RiotSharp.MatchEndpoint.MatchReference'.

-  Using GetLeagues method

```c#
var leagues = await _api.GetLeaguesAsync(RiotSharp.Misc.Region.eune, summoner.Id);
```

throws error

> 403, Forbidden

**Comment by JanOuborny** [comment]
> Error setting value to 'Season' on 'RiotSharp.MatchEndpoint.MatchReference'.
This should be fixed in #517
