### ISSUE TITLE
GetCurrentGame() How do i stop "404 Resource not found" when player isn't in a match?

### ISSUE THREAD

**Issue by JaeteeDev** [BenFradet/RiotSharp#523]
This is what i have but i'm not sure why the riot exception catch does nothing? all this does is crash the application when the player isn't in a game 
```  
public void getGame()
{
	var match = api.GetCurrentGame(RiotSharp.Misc.Region.oce, summoner.Id);
	var gameId = match.GameId.ToString();
	var players = match.Participants;
	try
	{
		if (gameId != null)
		{
			MessageBox.Show("Game Found");
		}
	}
	catch (RiotSharpException)
	{
		MessageBox.Show("Game Not found!");
	}
}
```

**Comment by BryanHitchcock** [comment]
The code you have before the try/catch block is what would cause an exception to be thrown if the player is not in a game.

**Comment by BenFradet** [comment]
@JaeteeDev Did wrapping the `api.GetCurrentGame` call inside the try/catch block solve your issue?

**Comment by JaeteeDev** [comment]
Yes thank you. I'm still new to coding so using the wrapper to create my first program. :)

Thanks guys!
