### ISSUE TITLE
Static part of the lib failing

### ISSUE THREAD

**Issue by Sossenbinder** [BenFradet/RiotSharp#529]
Hi!

I just downloaded your library and followed your readme so far.

What I'm currently trying is to download static data with your library, like this:

`StaticRiotApi m_staticRiotApi = StaticRiotApi.GetInstance(m_apiKey);`

 `var test = m_staticRiotApi.GetChampions(Region.euw);`

However, this always leaves me with an HttpRequestException.

I have seen that the demo page riot is offering uses totally different request urls compared to your library. Am I using this wrong, or is there a problem with static data?

**Comment by BenFradet** [comment]
What does the http request exception say?

**Comment by JaeteeDev** [comment]
Im guessing the same as mine as im having the same problem. Im getting the "429 Rate Limit Reached".In the riot Documentation it says you can only have 10 requests/hr. how would you get your application to Retrieve Champion data from 10 requests?

**Comment by Sossenbinder** [comment]
AuthenticationException: The remote certificate is invalid according to the validation procedure

That is the innermost exception and it seems like it's the cause. I tried to access the URL (https://global.api.pvp.net/api/lol/static-data/euw/v1.2/champion?locale=en_US&api_key=<key>) manually and it does not seem to work as well.

**Comment by JanOuborny** [comment]
There is a new version of the static data endpoint. Therefore the old links doesn't work anymore and need to be updated.

**Comment by Sossenbinder** [comment]
Yeah, that's what I thought when looking at the endpoints listed in the api

**Comment by JanOuborny** [comment]
I'm on it. I'm gonna have a fix in probably one hour.

**Comment by Sossenbinder** [comment]
Awesome!

**Comment by JanOuborny** [comment]
The develop branch is already up to date. You can build your own package with the instructions provided in the README.

**Comment by Sossenbinder** [comment]
I just downloaded the develop branch and built it, but when I try to generate a RiotApi object with `RiotApi.GetInstance(m_apiKey, 20, 100);`

I receive a FileNotFoundException with System.Net.Http :(

**Comment by JanOuborny** [comment]
Are you using it in an ASP.NET MVC project?

**Comment by Sossenbinder** [comment]
Yes, I use it in ASP.NET MVC, exactly

**Comment by JanOuborny** [comment]
You might want to check your assembly binding.
