### ISSUE TITLE
Deprecate RecentMatches

### ISSUE THREAD

**Issue by UghThatGuyAgain** [BenFradet/RiotSharp#537]
The recent matches endpoint (/lol/match/v3/matchlists/by-account/{accountId}/recent) is being deprecated, and the alpha endpoint (/lol/league/v3/mmr-af/by-summoner/{summonerId}) is already added.

**Comment by UghThatGuyAgain** [comment]
I suppose the alpha endpoint with mmr shouldn't be added, it's likely going to be removed anyways (it's a meme endpoint). Not sure why I bothered mentioning it.

**Comment by BryanHitchcock** [comment]
@BenFradet This should be closed as the additional endpoint was an April Fools joke and no longer exists.

**Comment by UghThatGuyAgain** [comment]
@BryanHitchcock The [deprecation of recent matches](https://discussion.developer.riotgames.com/questions/5130/deprecating-the-recent-games-endpoint.html) still stands.
