### ISSUE TITLE
GetRecentMatches throws a Newtonsoft excepton

### ISSUE THREAD

**Issue by TheFizz** [BenFradet/RiotSharp#540]
Not sure if it's a RiotSharp issue, but

```
//////
1.            var summoner = api.GetSummonerByName(RiotSharp.Misc.Region.ru, "thefizz");
2.            var rec = api.GetRecentMatches(RiotSharp.Misc.Region.ru, summoner.AccountId);
3.            var match = api.GetMatch(RiotSharp.Misc.Region.ru, rec[0].GameId);
/////
```

this code throws an exception on line 2

`Newtonsoft.Json.JsonSerializationException: "Error setting value to 'Season' on 'RiotSharp.MatchEndpoint.MatchReference'."`

any ideas ?

Give me a clue if I can fix this or the other way to get `HighestAchievedSeasonTier`

**Comment by BenFradet** [comment]
yup I need to release 3.0.2, if you build from develop it should be fine though

**Comment by BenFradet** [comment]
`task.Result` should just do what a sync version would, that's what we use in the unit tests.

Can you paste the whole exception for the `GetVersionsAsync` call?

**Comment by BenFradet** [comment]
mmh weird, can you try finding out at which level the exception happens? if it's from inside the `GetVersionsAsync` call or outside?

**Comment by TheFizz** [comment]
I used my wrapper for it and I also got an exception when trying to execute ` Task.Wait()` so IMO this can come out even from `System.Threading` but I might be wrong

**Comment by Kirides** [comment]
I think this issue should be closed, it contains no useful information, and the API changed since then.

currently the following code (Task.Result, bad practice, should use async/await, since already inside event) runs fine inside a win-forms "Button1_Click"
```cs
var api = RiotSharp.RiotApi.GetDevelopmentInstance(apiKey);
List<string> versions = null;
try
{
    versions = api.StaticData.Versions.GetAllAsync().Result;
}
catch (Exception ex)
{
    // Exception happened
    listBox1.Items.Add(ex.Message);
    return;
}

listBox1.Items.Clear();
foreach (var v in versions)
{
    listBox1.Items.Add(v);
}
```

**Comment by BenFradet** [comment]
cool thanks :+1: , closing
