### ISSUE TITLE
Getting Rank from a match?

### ISSUE THREAD

**Issue by Vertana** [BenFradet/RiotSharp#549]
Is there a built-in method or property that surfaces the rank a player got in a match? I have a function that retrieves a lot of information from the most recent match of a given account, but for the life of me I can't seem to find out how to get the rank they achieved. I'd like to know if they got an S+, A-, etc.
If not, any pointers as to how this might be achieved?

**Comment by BryanHitchcock** [comment]
Getting a summoner's grade in a match is not possible due to it being classified as private data.

**Comment by Vertana** [comment]
That makes sense to me. I wasted way too much time on this issue and never made any real headway. Do you have any idea how third party websites are able to show that data though ? That was my logic going in - if they can display the data, there has to be a way for me to do it as well. Or are they just making guesses based on available data such as CS, gold, KDA?

**Comment by BryanHitchcock** [comment]
I'm sure they are using their own algorithm to determine a letter grade.

**Comment by Vertana** [comment]
That actually makes me feel more comfortable with my assumptions. Thank you, I'll close this issue so it doesn't stick around forever.
