### ISSUE TITLE
Most of the tests are failing

### ISSUE THREAD

**Issue by CurlyBraceTT** [BenFradet/RiotSharp#552]
I don't have the tournament API key, only the dev api key.

![image](https://user-images.githubusercontent.com/8270922/41115786-38d6485e-6a91-11e8-9e41-41ac68744ab7.png)

Is this how its supposed to be? I suggest maybe we can add some visual studio test playlists to separate test categories.

**Comment by BenFradet** [comment]
We never got around to fixing them 😢

**Comment by CurlyBraceTT** [comment]
@BenFradet I will try to look at them then.

**Comment by BenFradet** [comment]
Thanks a lot much appreciated, feel free to go about it incrementally so we can accept smaller changes faster :+1:

**Comment by CurlyBraceTT** [comment]
@BenFradet btw do you know if Riot Games provide Tournament Api left and right? Seems like I do have to apply a product to get it.

When you build lib, how are the Tournament Api tests doing? All pass? Here is the list:

```
CreateProviderAsync_CreateTournamentAsync_CreateTournamentCodeAsync_UpdateTournamentCodeAsync_Test
CreateTournamentCodesAsync_CountGreaterThan1000_ThrowsArgumentException
CreateTournamentCodesAsync_CountLessThan1_ThrowsArgumentException
CreateTournamentCodesAsync_InvalidTeamSize_ThrowsArgumentException
```

**Comment by BenFradet** [comment]
The last time I applied for one I had to say that I was the maintainer of this repo but the api key is now expired unfortunately.

**Comment by BenFradet** [comment]
I think, given the hassle it is to get those api keys, those tests should be disabled by default
