### ISSUE TITLE
Remove Runes&Masteries Endpoints?

### ISSUE THREAD

**Issue by CurlyBraceTT** [BenFradet/RiotSharp#553]
Following #552 

We have tests which are falling because runes&masteries api was removed due to massive rework a while ago.
```
GetRunePagesAsync_ExistingSummonerId_HasRunePages
GetRunePagesAsync_InvalidSummonerId_ThrowsResouceNotFound
GetMasteryPagesAsync_ExistingSummonerId_HasMasteryPages
GetMasteryPagesAsync_InvalidSummonerId_ThrowsResouceNotFound
```
From https://discussion.developer.riotgames.com/articles/3779/runes-reforged-changes-in-the-riot-games-api.html
>this means we’ll be deprecating runes-v3 and masteries-v3 with no replacement. Runes Reforged data will be included in both the active game and match data.

I suggest we remove these Endpoints as well as tests. I will submit PR if you are ok.

**Comment by BenFradet** [comment]
Agreed :+1:
