### ISSUE TITLE
Timeline not accessible from MatchEndpoint

### ISSUE THREAD

**Issue by Bobsleigh** [BenFradet/RiotSharp#560]
According to the old doc, there used to be a boolean to the `GetMatch(Region, Int64, Boolean)` method to request the timeline. The boolean is no longer in the method and there doesn't seem to be a way to access a match Timeline anymore.

**Comment by BenFradet** [comment]
yes the doc needs to be updated

**Comment by Bobsleigh** [comment]
Is there currently a way to access the Timeline info throught RiotSharp?

**Comment by BenFradet** [comment]
I might be wrong but I think it was removed?

**Comment by cornerstone-programming** [comment]
In RiotSharp I could not find a function.
Riot provides this function with an own API:
/lol/match/v3/timelines/by-match/{matchId}
https://developer.riotgames.com/api-methods/#match-v3/GET_getMatchTimeline

**Comment by adfinlay** [comment]
I was also wondering if this could be added back in and a new release pushed to Nuget? The timeline v3 endpoint is very much still active.

**Comment by QiushiZhu** [comment]
Would love to see timeline API added back!
