### ISSUE TITLE
Get Summoner Ranked League

### ISSUE THREAD

**Issue by stefancreed37** [BenFradet/RiotSharp#562]
Anyone have idea how to get summoner ranked league? (bronze, silver, gold etc.)

Here's what I've done so far.

![screenshot_1](https://user-images.githubusercontent.com/39136351/42137131-5c2745fe-7d67-11e8-9f95-f5711445a0e5.png)

I want to get summoner league to label (bronze, silver, gold etc.), and LP (if possible).

Thank you..

**Comment by BryanHitchcock** [comment]
You can retrieve a player's ranked information by using the `GetLeaguePositions` or `GetLeaguePositionsAsync` method. 

For example:

![](https://i.imgur.com/Y23Aft6.png)

**Comment by stefancreed37** [comment]
It helps so much. And yes it works. But guess what. Only when someone is in game, and I try to gather ranked information data about that summoner, I get everything, BUT, when summoner is not in game, I don't get ranked data.

Picture Number 1: Summoner is in-game
![screenshot_2](https://user-images.githubusercontent.com/39136351/42154227-7d59474e-7de5-11e8-84d4-8e96281aa903.png)
-----------------------------------------------------------------------

Picture Number 2: Summoner is not in-game.
![screenshot_3](https://user-images.githubusercontent.com/39136351/42154280-98fb04e2-7de5-11e8-8536-44dcd9451b43.png)
-----------------------------------------------------------------------

**Comment by BryanHitchcock** [comment]
Hmm, that shouldn't be the case. It's likely you have a bug within your application/business logic as querying for league positions doesn't rely on a user to be in-game.

Here's a modified version of the above code that demonstrates this using the same summoner name as your second screenshot:

![](https://i.imgur.com/piNY0nn.png)

**Comment by stefancreed37** [comment]
No bro, still nothing. I've tried to make button async, but doesn't work.
It gets level, summoner, region, ID, but can't get RANKED Data {Tier, LP}.

![screenshot_4](https://user-images.githubusercontent.com/39136351/42173804-85209da2-7e20-11e8-8cd2-a271156e2d49.png)

**Comment by BryanHitchcock** [comment]
The issue is that `var rec = api.GetCurrentGame(RiotSharp.Misc.Region.eune, summoner.Id);` is throwing the NotFound exception, and as a result, your league position code is not being executed. Moving that line to the end of the try block and it'll work. 

Also, I suggest learning how to use the debugger to find issues such as this one in the future. Let me know if you have any other questions and/or problems.

**Comment by stefancreed37** [comment]
Well, just that copy - paste code was problem. Huh. It works now. I'm sorry if I was annoying, but this was stopping me to do anything in further for this application. Thank you for the help mate.
And yes, is possible to get summoner icon to PictureBox?

**Comment by BryanHitchcock** [comment]
[Yes.](https://developer.riotgames.com/static-data.html)

**Comment by stefancreed37** [comment]
I did it for icons too. 
Thank you for help.
(You can close this).


![screenshot_6](https://user-images.githubusercontent.com/39136351/42176096-1d590b3e-7e28-11e8-9a68-d9414cb2274a.png)

**Comment by BenFradet** [comment]
Thanks for the help @BryanHitchcock :+1:
