### ISSUE TITLE
Summoner - Skins, Champions

### ISSUE THREAD

**Issue by stefancreed37** [BenFradet/RiotSharp#563]
Is it possible to get data about how many champions and skins summoner have?
And which skins have?

**Comment by cornerstone-programming** [comment]
I remember the time of elophant. there you had an own program to run to sync your own skins with the database of elophant. Therefore I believe there is no API for this.

For champions you might use the mastery points per champion to identify champions a player definitively own - or at least owned once.

**Comment by JanOuborny** [comment]
Skins are most likely considered private data. Therefore, there won't be an endpoint for this data.

**Comment by stefancreed37** [comment]
Oh, okay.
(Close)
