### ISSUE TITLE
Deprecation of the lol-static-data-v3 API

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#564]
Ref: https://discussion.developer.riotgames.com/articles/5719/removal-of-the-lol-static-data-v3-api.html

**Comment by JanOuborny** [comment]
I'm gonna rename all StaticData references to `DDragon` and remove the `Static` suffix from the corresponding classes.

@BenFradet Are you fine with this?

**Comment by BenFradet** [comment]
sounds like a plan :+1:

**Comment by JanOuborny** [comment]
@CurlyBraceTT Do you want to migrate the static data tests when I'm done migrating the api?

**Comment by CurlyBraceTT** [comment]
@JanOuborny Sure.

**Comment by JanOuborny** [comment]
@CurlyBraceTT I'm done migrating now. It's not tested yet, but the signatures of the methods are final, so you can start with the tests now. The changes are in the `ddragon-migration` branch. When you are done, just start are PR against that branch.

**Comment by CurlyBraceTT** [comment]
@JanOuborny Done.

Some Notes:
* I fixed Champion Endpoint a little.
* Champion json model probably needs to be fixed, GetChampionAsync returns empty object
* I am not sure if Runes Endpoint makes sense (Its about old rune system which existed long time ago, new runes are being referenced as Reforged) This needs to be checked

List of the failing tests for now:
* GetChampionAsync_Test
* GetSummonerSpellsAsync_Test
* GetMapsAsync_Test
* GetMasteriesAsync_Test
* GetRunesAsync_Test
