### ISSUE TITLE
MatchId not in MatchReference

### ISSUE THREAD

**Issue by tpercario** [BenFradet/RiotSharp#565]
The documentation states that there is a MatchId variable in the MatchReference but there is no such variable in the class.

**Comment by JanOuborny** [comment]
Looking into the docs, I can't find a `matchId` field. However, the `gameId` field should be an equivalent of the `matchId` field. You can use it to query the match details.

![image](https://user-images.githubusercontent.com/12223382/42571474-8b95275e-8517-11e8-819a-76b5f2687a7c.png)
