### ISSUE TITLE
Platform is occasionally lowercase - converter should handle this

### ISSUE THREAD

**Issue by adfinlay** [BenFradet/RiotSharp#575]
I received some exceptions about not being able to set PlatformId on Participant and looked at the data - `currentPlatformId` was "na1" instead of "NA1". Changing 

https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Converters/PlatformConverter.cs#L21

to `var str = token.Value<string>().ToUpperInvariant();` seems to fix it.

**Comment by Turbinya** [comment]
https://github.com/BenFradet/RiotSharp/blob/cee21c6066c9ba96a3490d6020e66a96a7718fd9/RiotSharp/Misc/Converters/PlatformConverter.cs#L21 
Two end-of-line characters
