### ISSUE TITLE
Remove deprecated champion endpoint

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#581]
Ref: 
- https://developer.riotgames.com/api-methods/#champion-v3/GET_getChampions
- https://developer.riotgames.com/api-methods/#champion-v3/GET_getChampionsById

**Comment by blackben1992** [comment]
Hello, I'd like to take this one if it's currently unassigned. First time contributing to open source but I feel like I can handle this.

**Comment by tobithegreat** [comment]
I'd like to get this done, if no one else is working on it!

**Comment by dsychin** [comment]
Is this issue still open?
I'd like to give this a try.
Am I correct in understanding that I need to remove the old champions url and the functions that uses it from RiotSharp.Endpoints.ChampionEndpoint?

**Comment by BenFradet** [comment]
yup :+1:
