### ISSUE TITLE
Remove old Runes / Masteries from CurrentGame Endpoint and add Runes Reforged[Perks] + StaticApi

### ISSUE THREAD

**Issue by lorexzer0** [BenFradet/RiotSharp#588]
- [x] The old runes / masteries system is removed from league so they should be removed from the CurrentGame.Endpoint, altough u can still find data about them in older matches so they should stay in the Match.Endpoint. 
- [x] Add Perks to the CurrentGame.Endpoint so the runes can be aquired.
- [x] Use "[ddragon](http://ddragon.leagueoflegends.com/cdn/8.20.1/data/en_US/champion.json)" for static data endpoint. More about that here: [Static Data](https://developer.riotgames.com/static-data.html)

**Comment by cornerstone-programming** [comment]
Regarding second point "ddragon"

I m wondering if riotsharp is just a wrapper for riotapi or if ddragon will be part as well.

**Comment by JanOuborny** [comment]
The latest build already contains a wrapper for the ddragon data, which was provided in the static data endpoint.
