### ISSUE TITLE
[Question] 403 in GetLeagues()

### ISSUE THREAD

**Issue by takoz53** [BenFradet/RiotSharp#598]
I keep getting 403, Forbidden when I try to use GetLeagues() in the code
 as follows:

        private void getLeague()
        {
            try
            {
                List<RiotSharp.LeagueEndpoint.League> currentLeague = api.GetLeagues(RiotSharp.Misc.Region.euw, summoner.Id);
                var leagueTier = currentLeague[0].Tier.ToString();
                var leaguePoints = currentLeague[0].Entries[0].LeaguePoints;
                Console.WriteLine("League :" + leagueTier + " " + leaguePoints);
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error happened while fetching the League Information: " + ex.Message);
            }
        }
`

my api is instantiated in the Constructor and I can get other info with it (such as current game) and my summoner is also declared in the Constructor and saved as an attribute. I use the development API Key and have no Idea why I keep getting 403s. Any ideas?

**Comment by spyker0** [comment]
Here is working normally, by your code I see that you aren't on the last version.
You should download the last version (develop branch) and pack the project to get this working.
The code will look like this
```c#
var leaguePosition = await api.League.GetLeaguePositionsAsync((Region)regiao, summoner.Id);
```
We need to update the documentation and also the readme 😢

**Comment by takoz53** [comment]
thank you I'll give it a shot.

**Comment by BenFradet** [comment]
Feel free to open PRs against the readme :+1:

**Comment by spyker0** [comment]
I'll do someday
