### ISSUE TITLE
Error since some minutes?

### ISSUE THREAD

**Issue by denniskai1234** [BenFradet/RiotSharp#600]
Hey,

my tool worked fine like 30 mins ago, but now as soon as i execute the Match.GetMatchListAsync function and want to get any results from it, it throws me this error:
JsonSerializationException: Error setting value to 'Season' on 'RiotSharp.Endpoints.MatchEndpoint.MatchReference'.

Small code to show the issue:

`                var summoner = api.Summoner.GetSummonerByNameAsync(RiotSharp.Misc.Region.euw, "pitpat1337");
                Console.WriteLine("Summoner Name: " + summoner.Result.Name);
                Console.WriteLine("Summoner Level: " + summoner.Result.Level);
                Console.WriteLine("Summoner Id: " + summoner.Result.Id);
                var pepe = api.Match.GetMatchListAsync(RiotSharp.Misc.Region.euw, summoner.Result.AccountId);
                Console.WriteLine("Total Games played: " + pepe.Result.TotalGames);`

Any idea why this is happening?

**Comment by BenFradet** [comment]
Yup, there might be a new season, I'd suggest checking what the api gives back directly and compare that to the seasons we support: https://github.com/BenFradet/RiotSharp/blob/4474dc4762a8d4ff60b2f35d5828b828c28ae13a/RiotSharp/Endpoints/MatchEndpoint/Enums/Season.cs.

Most likely we need a 2019 season.

**Comment by denniskai1234** [comment]
/// <summary>
        /// Pre season 2019.
        /// </summary>
        PreSeason2019 = 12,

        /// <summary>
        /// Season 2019.
        /// </summary>
        Season2019 = 13

After adding those two things in the season enums + convert it works again, thanks!

**Comment by BenFradet** [comment]
cool, feel free to open a pr :+1:

**Comment by denniskai1234** [comment]
Someone else was faster as i went to bed at that time 👍 

Not sure if i should open another issue for this one, but Stats.MinionsKilled returns always 0 for me, no matter what player im checking.

**Comment by spyker0** [comment]
I think you should open another issue.
