### ISSUE TITLE
Minions killed always returns 0

### ISSUE THREAD

**Issue by denniskai1234** [BenFradet/RiotSharp#602]
As the Topic says, no matter how many minions were kiled in a game, Stats.MinionsKilled will always return 0 for me.

**Comment by BenFradet** [comment]
You'll need to compare with the raw payloads sent back by the API to check if they are indeed 0 or if there is an issue when deserializing the field, e.g. the field might be misnamed

**Comment by denniskai1234** [comment]
As far as i can see the api returns it as :

                "totalMinionsKilled": 52,

**Comment by denniskai1234** [comment]
Alright anoher simple fix: change minionsKilled to totalMinionsKilled and its woking again.

**Comment by BenFradet** [comment]
yup was typing just that :+1:
