### ISSUE TITLE
Cant Get the VisionScore 

### ISSUE THREAD

**Issue by Tobias3107** [BenFradet/RiotSharp#610]
Hey Guys,
I cant find the VisionScore in the ParticipantsStats. I look in the Documentation and there is also nothing what show me like the VisionScore. I thing this isnt available.
Maybe a Bug? or i didnt see it?
![dsada](https://user-images.githubusercontent.com/33278260/55686934-89358380-5967-11e9-9c93-270d8b32be5f.PNG)

**Comment by JanOuborny** [comment]
You are right. The property is missing from `ParticipantStats`. I fixed it in my latest PR. It should be merged soon.

**Comment by JanOuborny** [comment]
Should be fixed now in the latest release. @Tobias3107
