### ISSUE TITLE
Wrong Region on MatchReference

### ISSUE THREAD

**Issue by Tobias3107** [BenFradet/RiotSharp#614]
Hey, I have seen a Wierd bug. Where the Region not shown right.

![MatchReference Vergleich](https://user-images.githubusercontent.com/33278260/55841616-2d6a2680-5b30-11e9-87ac-11f178aa73c3.PNG)
![MatchReference Code Vergleich](https://user-images.githubusercontent.com/33278260/55841671-64d8d300-5b30-11e9-8d71-c7d1ca59df90.PNG)

>'foreach (MatchReference mr in l[q].Matches)
                {
                    Console.WriteLine(mr.Timestamp);
                    Console.WriteLine("------------------------------------");
                    Console.WriteLine("Queue " + (LQueue)mr.Queue);
                    Console.WriteLine("Region " + mr.Region + " -- " + p.Region);
                    Console.WriteLine("Rolle " + mr.Role);
                    Console.WriteLine("Lane " + mr.Lane);
                    Console.WriteLine("Season " + mr.Season);
                    Console.WriteLine("GameId " + mr.GameId);
                    Console.WriteLine("------------------------------------");
                    Match m = api.Match.GetMatchAsync(p.Region, mr.GameId).Result;
                    TimeSpan t = m.GameDuration;
                }`

**Comment by JanOuborny** [comment]
Can you attach the raw json from the match list endpoint?

**Comment by Tobias3107** [comment]
The Complete Request from My Matches
[Queue420-Bug-BR.txt](https://github.com/BenFradet/RiotSharp/files/3071311/Queue420-Bug-BR.txt)
