### ISSUE TITLE
Looking for code how to handle exception

### ISSUE THREAD

**Issue by kwiatkos0** [BenFradet/RiotSharp#618]
Hello,

I'm looking for C# example code of handling exception when Summoner with given name doesn't exists. I'm trying to make ASP.NET MVC app and i'm also not sure where this exception should be handled, in Controller or Model.

I tried with something like this:

```
 try
        {
                var api = RiotApi.GetDevelopmentInstance(ApiCode);

                if (String.IsNullOrWhiteSpace(name))
                    return View("Search");
                else if (api.Summoner.GetSummonerByNameAsync(Region.Eune, name) != null)
                {
                    var summoner = new Summoner(name, ApiCode);
                    return View(summoner);
                }
                else
                {
                    return View("Error");
                }

            }
 catch (RiotSharpException ex)
            {
                if(ex.HttpStatusCode == HttpStatusCode.BadRequest)
                    return View("Error");
                else if(ex.HttpStatusCode == HttpStatusCode.NotFound)
                {
                    return View("Error");
                }
                else { }
                return View("Error");
                
            }
```

I want to move user to special error page when summoner is not found.
 I'm beginner and have no idea how to do it, i tried few ways but no one works.

Thanks for help.

**Comment by JanOuborny** [comment]
You are already on a good way. You should place all of your logic inside the controller actions and therefore handle all exceptions inside the controller.

When the summoner is not found you can either redirect to an custom error action, e.g. `Home/SummonerNotFound`. This will change the url in your browser. 

Or you can return a different view `return View("SummonerNotFound")`. That will keep the current url.

**Comment by kwiatkos0** [comment]
So all methods shouldn't be in the for ex. SummonerModel? At this moment all calls and methods i have in SummonerModel. Here i want to check if summoner exists. When i try to do
`var summ = api.Summoner.GetSummonerByNameAsync(Region.Eune, name).Result;`
Before if construction in try block I have this error:
https://imgur.com/Cb17jvP

Everything works fine when Summoner is found.

And if i delete this and try again I get error at this part:

```
if (String.IsNullOrWhiteSpace(name))
                    return View("Search");
                else if (api.Summoner.GetSummonerByNameAsync(Region.Eune, name) != null)
                {
                    Summoner summoner = api.Summoner.GetSummonerByNameAsync(Region.Eune, name).Result;
                    var show = new SummonerData(name, ApiCode, summoner);
                    return View(show);
                }
                else
                {
                    return View("Error");
                }
```

**Summoner summoner = api.Summoner.GetSummonerByNameAsync(Region.Eune, name).Result;**


Is there any way to get HttpResponseCode from calling ^ this?

**Comment by vizo92** [comment]
And if i delete this and try again I get error at this part:

```
if (String.IsNullOrWhiteSpace(name))
                    return View("Search");
                else if (api.Summoner.GetSummonerByNameAsync(Region.Eune, name) != null)
                {

                    **Summoner summoner = api.Summoner.GetSummonerByNameAsync(Region.Eune, name).Result;**
                    var show = new SummonerData(name, ApiCode, summoner);
                    return View(show);
                }
                else
                {
                    return View("Error");
                }
```

**Comment by kwiatkos0** [comment]
I have finally found solution/work around.
```

catch (RiotSharpException ex)
            {
                return View("Error");
            }

```
is not working in case when summoner does not exist. Bad request is handled by:
```

            catch (AggregateException ex)
            {
                return View("Error");
            }

```
