### ISSUE TITLE
PlayerOrTeamName is Null

### ISSUE THREAD

**Issue by santutu** [BenFradet/RiotSharp#619]
League.GetLeaguePositionsAsync

![image](https://user-images.githubusercontent.com/28470293/56468280-2b279680-6465-11e9-8d98-55d8b459ca94.png)

**Comment by JanOuborny** [comment]
Thanks for pointing this out. `GetLeaguePositionsAsync` is now deprectated (by Riot), therefore, we are not fixing this bug. This method will be removed in the next version.

**Comment by kirides** [comment]
This will be fixed/replaced once #622 is merged
