### ISSUE TITLE
Update league endpoint

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#621]
Add
- `/lol/league/v4/entries/by-summoner/{encryptedSummonerId}`
- `/lol/league/v4/entries/{queue}/{tier}/{division}`
- `/lol/league/v4/grandmasterleagues/by-queue/{queue}`
- `/lol/league/v4/leagues/{leagueId}`

Remove:

- `GetLeaguePositionsAsync`

Ref:
https://developer.riotgames.com/api-methods/#league-v4/GET_getLeagueById

**Comment by kirides** [comment]
I'll take a look at it.
Might be done by tomorrow :wink:
