### ISSUE TITLE
GetChallengerLeagueAsync has incorrect modal

### ISSUE THREAD

**Issue by lian-ders** [BenFradet/RiotSharp#623]
When im calling `await api.League.GetChallengerLeagueAsync(Region.Euw, Queue.RankedSolo5x5);` the enties modal looks like this: 

![image](https://user-images.githubusercontent.com/4692299/56808487-eb302d00-6831-11e9-9598-3213af26d34c.png)

As you can see `leagueName` is null for all entries. I think this is because the Riot api defines this property as `summonerName` and also `summonerId`, which is missing. Changing the region or queue doen't change the result.

I think that this might be a bug since the `LeaguePosition` model doesn't corresponds with the RiotApi model.

**Comment by kirides** [comment]
this will be fixed with merging #622

**Comment by kwiatkos0** [comment]
Fixed with #627
