### ISSUE TITLE
RiotSharpException should include more information.

### ISSUE THREAD

**Issue by Yawnder** [BenFradet/RiotSharp#629]
I'm trying to deal with the (in)famous 429 exception. For the time being, I don't want to interfere with the code since I don't know how my needs transpose to others (async, non async, retries, automatic delays, etc., etc.), so I'm just making a tiny wrapper to handle these exception, but I have nothing to work with. Yes, the limit is exceeded, but the request that failed is supposed to include the information in the header to let you know when to retry-ish.
Would it be possible to surface that, or is it too deep?
One day I might send in a PR, but not yet!

**Comment by BenFradet** [comment]
I think that's definitely worth doing :+1:

**Comment by Yawnder** [comment]
Thanks sir!
