### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by TheExeQ** [BenFradet/RiotSharp#637]
Is there a discord server related to RiotSharp?

**Comment by matheusavi** [comment]
I see many people on riot developers discord server talking about riot
sharp (and other libraries).

**Comment by JanOuborny** [comment]
Creating a RiotSharp discord server could help to concentrate these loose discussions and questions. What do you think @BenFradet?

**Comment by BenFradet** [comment]
yup good idea, I'll see what I can do after the holidays

**Comment by AxharKhan** [comment]
Yes a discord server would be great. :)

**Comment by BenFradet** [comment]
Created one here https://discord.gg/w6U8ke :+1:
