### ISSUE TITLE
League API - GetLeaguePositionsAsync() 403 Forbidden

### ISSUE THREAD

**Issue by Bari77** [BenFradet/RiotSharp#646]
Hello,

I got an "403, Forbidden" when I do this :

`return await riotApi.League.GetLeaguePositionsAsync((Region) userGame.Region, userGame.IdSummoner);`

userGame.IdSummoner => My encrypted summoner id (-tephjJbG02qRGBQCLoDLam2-HYow7guDfZssEsk2kVLwL0)
userGame.Region => My region (EUW)

In another part of my app, I use my dev api key too for Summoner endpoint, and it's correcly work, so isn't API key problem.

Can you help me please ?

Cordialy, Bari.

PS : On developer.riotgames.com web site, this call works fine.

**Comment by xXLAOKOONXx** [comment]
Do you use the current build?
If you use the nugget package this won t work.
You need to build your own nugget package to be up to date.

**Comment by Bari77** [comment]
I used nugget package version, but I don't understand what you mean, why the all other method working except her ?

**Comment by xXLAOKOONXx** [comment]
Riot updated their api from 
`"/positions/by-summoner/{0}"`
to
`"/entries/by-summoner/{0}"`

for more information take a look into the issue regarding league api update: 
#621

**Comment by Bari77** [comment]
Ok, now I understand, it was fixed on a pull request no ? Then why this feature isn't already versionned on nugget packet ? Is this lib unmaintained ?

**Comment by MingweiSamuel** [comment]
The nuget package is unmaintained, but the github repository _is_ maintained.

**Comment by Bari77** [comment]
Ok, so I followed instructions :
![image](https://user-images.githubusercontent.com/20283367/73564853-c7ed7a80-4460-11ea-9694-955de6f57222.png)
 any idea ?
PS: My bad, i runned in solution folder, not project folder. Can be closed.
