### ISSUE TITLE
Adding Clash Endpoint

### ISSUE THREAD

**Issue by Rezga12** [BenFradet/RiotSharp#663]
Hi,
I noticed that the project is missing **The Clash Endpoint:** 

https://developer.riotgames.com/apis#clash-v1

I'm interested on working on this feature, but I am new to open source world and I'm not really sure if I should notify anyone about me working on this Issue or should I just submit a **PR** after I finish with my implementation.

Thanks.

**Comment by BenFradet** [comment]
Hello,

I think logging an issue saying you started working on it is a good approach, it avoids unnecessary duplicated work :+1:
