### ISSUE TITLE
Exeption when summoner name is inccorrect

### ISSUE THREAD

**Issue by jacob7395** [BenFradet/RiotSharp#672]
This has probably already meen addressed but when calling GetSummonerByNameAsync from the SummonerEndpoint with a name that don't exist within that reagion a RiotSharpException is thrown. I'm sure this is intentaly but with c# 8 nullable you could start returning null summoners. However this update would badly effect the current user base as they probly expect the exeption. 

Its something to keep in mind going forward.

**Comment by BenFradet** [comment]
I'm :+1: on avoiding unnecessary exceptions
