### ISSUE TITLE
RiotSharp goal

### ISSUE THREAD

**Issue by EmanueleSpadaro** [BenFradet/RiotSharp#679]
Hi,
I just wanted to make a quick question regarding RiotSharp.
(Off-Topic: I just realized that you cannot put labels to issues if you're not a contributor, therefore I couldn't put 'Question' label)

What is the future goal of RiotSharp?
Because I find the name kind of misleading if you consider that Riot has plently of games nowadays and you're only implementing features for League APIs. What about renaming it to LeagueSharp or something?

**Comment by BenFradet** [comment]
Originally, I named it RiotSharp because I thought it sounded better than LeagueSharp.
Additionally, I'm not against supporting other APIs.
