### ISSUE TITLE
Matchinfo GameDuration is incorrect when using Match-v5

### ISSUE THREAD

**Issue by Lunariz** [BenFradet/RiotSharp#694]
Grabbing info for a game is giving me a match duration of 2 days, 8 hours and 26 minutes.
I assume there is a milliseconds/seconds conversion going wrong somewhere!

I checked this game in particular, which happens to be a remake: EUW1_5394536774
API call gives Gameduration = 203157, which is 2:30 when parsed as milliseconds (correct) but 2d8h when parsed as seconds.

**Comment by xXLAOKOONXx** [comment]
You are completely write, conversion uses a seconds converter here https://github.com/BenFradet/RiotSharp/blob/95ec347911316869a12e0a101623c81a76252b5f/RiotSharp/Endpoints/MatchEndpoint/MatchInfo.cs#L27
