### ISSUE TITLE
Error when getting match by game ID

### ISSUE THREAD

**Issue by Man16** [BenFradet/RiotSharp#707]
Hi,

Im using the fork by  @xXLaokoonXx .

I am attempting to use `Match.GetMatchAsync` which takes a region and the game ID.

Game IDs look like the following: EUW1_5839263580

I have tried both `Match.GetMatchAsync(Region.Euw, "EUW1_5839263580")` & `Match.GetMatchAsync(Region.Euw, "5839263580")` but i receive the following error: `RiotSharp.RiotSharpException: Bad request - Invalid routing value euw1`

**Comment by xXLAOKOONXx** [comment]
You need to use the region `Europe` for the match endpoint.
It might be a bit confusing, when to use what region.
To check out what kind of region is allowed for what endpoint check out [the developer platform](https://developer.riotgames.com/apis)

**Comment by xXLAOKOONXx** [comment]
`Match.GetMatchAsync(Region.Europe, "EUW1_5839263580")`
should be the right code

**Comment by Man16** [comment]
> 

That worked, thanks
