### ISSUE TITLE
Is there an api to send chat message in the game

### ISSUE THREAD

**Issue by arrebole** [BenFradet/RiotSharp#712]
Is there an api to send chat message in the game,

**Comment by arrebole** [comment]
It's in-game, not a select champion page

**Comment by xXLAOKOONXx** [comment]
RiotSharp is about the RiotAPI which is available as an endpoint without any client running.
What you are looking for might be the League Client API https://developer.riotgames.com/docs/lol#league-client-api
I recommend joining the Discord https://discord.gg/riotgamesdevrel as there is enough information and helpful links to investigate.
