### ISSUE TITLE
Bad request - Invalid routing value `region` for every Match methods

### ISSUE THREAD

**Issue by x0rld** [BenFradet/RiotSharp#713]
Hi,
I try to get some matches with the api but I always have an exception for "invalid routing value na1/euw1" depends on which region I try

I don't understand what is the issue with my code
```csharp
var summoner =await riotApi.Summoner.GetSummonerByNameAsync(Region.Na, "jAnna kendrick");
var matchlist = await  riotApi.Match.GetMatchListAsync(Region.Na,summoner.Id);
```

**Comment by AoshiW** [comment]
same as #707
[The AMERICAS routing value serves NA, BR, LAN and LAS. The ASIA routing value serves KR and JP. The EUROPE routing value serves EUNE, EUW, TR, and RU. The SEA routing value serves OCE.](https://developer.riotgames.com/apis#match-v5)

```cs
var matchlist = await  riotApi.Match.GetMatchListAsync(Region.Americas, summoner.Puuid);
```
Edit: and MAtch V5 use `Puuid`, not `Id`

**Comment by x0rld** [comment]
I have the same error with this code :/

**Comment by AoshiW** [comment]
that is weird, this code works for me:
```cs
var riotApi = RiotSharp.RiotApi.GetDevelopmentInstance(apiKey);
var summoner = await riotApi.Summoner.GetSummonerByNameAsync(Region.Na, "jAnna kendrick");
var matchlist = await riotApi.Match.GetMatchListAsync(Region.Americas, summoner.Puuid);
var match =  await riotApi.Match.GetMatchAsync(Region.Americas, matchlist[0]);
```

**Comment by x0rld** [comment]
it's fine,
I just did the api request myself with httpclient and it worked
