### ISSUE TITLE
SEA routing for OCE

### ISSUE THREAD

**Issue by DarkIntaqt** [BenFradet/RiotSharp#715]
If this change will not be made, fetching oce games would be not possible

**Comment by xXLAOKOONXx** [comment]
Feel free to implement the region yourself. The following locations might help you:
Enum: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Region.cs#L10
Translation for API: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Http/RequesterBase.cs#L147
JSON Support: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Misc/Converters/RegionConverter.cs

Create a fork, implement your changes and create a pull request and the feature might be available for everyone :)
