### ISSUE TITLE
GetChampionMasteryAsync Doesnt work.

### ISSUE THREAD

**Issue by yarlKot1904** [BenFradet/RiotSharp#727]
I'm facing a problem: I'm trying to get champion mastery, but I'm facing an error: 403(Forriben) what am I doing wrong? Here is my code:
`mastery = api.ChampionMastery.GetChampionMasteryAsync(Region.Ru, curSummoner.Id, particiant.ChampionId).Result;`

**Comment by xXLAOKOONXx** [comment]
I never used that part of the api and its long time I did anything with the api, but I recommend the following debugging:
- draw playerid and championid from your executing code
- try to reproduce the request within riots interactive api documentation

I guess you are using a bad api key (deactivated or insufficient permissions)

**Comment by AoshiW** [comment]
endpoints that used summonerID in ChampionMasteryV4 are deprecated (https://developer.riotgames.com/apis#champion-mastery-v4), new endpoints should use puuid, .. unfortunately there is little chance that RiotSharp will fix this bug, so the best solution is to find another library that is maintained

**Comment by Nicolas-Ding** [comment]
I stumbled upon this problem myself today and made a change to fix that: https://github.com/BenFradet/RiotSharp/pull/728

I'm not sure whether @BenFradet is still looking at this repo and if this PR will be merged anytime soon though
