### ISSUE TITLE
Wins/losses in ranked

### ISSUE THREAD

**Issue by ghost** [BenFradet/RiotSharp#78]
but when i search my summoner for wins and losses in soloq rankeds, i have 168 wins and not a single loss. I don't know if thats an error in your api or i just mixed something up, so here's my code:

var MySummoner = LoLApi.GetSummoner(Region.euw, "XXXXXXX");
List<RiotSharp.LeagueEndpoint.League> MySummonerLeagues = MySummoner.GetEntireLeagues();

List<RiotSharp.StatsEndpoint.PlayerStatsSummary> MySummonerStatsSummary = MySummoner.GetStatsSummaries();

string Losses = MySummonerStatsSummary[0].Losses.ToString(); //0
string Wins  = MySummonerLeagues[0].Entries[0].Wins.ToString(); //168

I dont want to bug you, but i dont know what to do :(

**Comment by GersuAlves** [comment]
@BenFradet Help me, 
PlayerStatsSummaryType not is a namespace? =\

**Comment by BenFradet** [comment]
@GersuAlves The stats endpoint has been removed by Riot
