### ISSUE TITLE
GetSummoner() hangs the program

### ISSUE THREAD

**Issue by Pawes1234** [BenFradet/RiotSharp#90]
In the last update everything worked fine. Now I'm stuck with this:
```c#
var api = RiotApi.GetInstance("my key here");
var summoner = api.GetSummoner(RiotSharp.Region.eune, "ign here");
```
If I'm creating a Console Application, the code runs & works fine.
However, in Windows Forms application, on the GetSummoner line the program just hangs.

**Comment by lolzitos** [comment]
Hi guys, Same problem here, the program get stucked when try to get information from API.

@BenFradet do you need some help to find the problem?

**Comment by BenFradet** [comment]
I pretty much know where the problem is coming from, the thing is I would have to revert the code in master to 783740e49b1127e15e9f8d2d4e03d6ac2f53eebc and I don't have much time to spare right now, unfortunately.
