### ISSUE TITLE
problem getting summoner.. :( please see this

### ISSUE THREAD

**Issue by itapi** [BenFradet/RiotSharp#92]
hey bro! first of all i would like to say ur library is awesome! it's an amazing work man.

i just started to use it and on my first steps i ecountered a problem.. i just tried to do as u said in the introduction to get a specific summoner..

   private void button1_Click(object sender, EventArgs e)
        {
            var api = RiotApi.GetInstance("xxx");

            try
            {
                var summoner = api.GetSummoner(RiotSharp.Region.eune, xxxx);
            }
            catch (RiotSharpException ex)
            {
                //Handle the exception however you want.
            }

        }

yeah that's my id and all.. hahaha(and the key :D)

there is no prob at the first line but then,when it enters the getsommer function its getting stuck... i used 
windows form and when i click the button and it's running the code its getting stuck at the try{} code...

i know it because i tried to show a messagebox after the "vap api.." line and its worked but after the 
try{} it didnt....

i dont think im missing somthing... everything looks good.. may u help me please? :smile: 

i really appriciate it bro
TYVM

**Comment by BenFradet** [comment]
Hey, thanks, it's a know issue, and I will have to revert some code once I get the time, see #90.

**Comment by itapi** [comment]
ohh srry bro yeahh didnt see it :smile:

**Comment by BenFradet** [comment]
I should be able to do it in one week or so.

**Comment by lolhaha1** [comment]
@BenFradet  we would all really like u to fix it bro... it's will help my project :smile: 
please fix it as soon as posibble :laughing:

**Comment by lolhaha1** [comment]
@BenFradet  yes bro we all would like you to fix is please as soon as posibble :smile: 
i really need it for my project bro :smiley: 

please fixxx ittt

**Comment by lolzitos** [comment]
@lolhaha1 , Please be patient, @BenFradet do this great work for free!

Also my project get blocked like yours, but we must be patient.

:)

**Comment by Corran-Raisu** [comment]
Ever since the problem showed up I reverted the RiotSharp reference I was using to 783740e49b as Ben mentioned in https://github.com/BenFradet/RiotSharp/issues/90 

I can't recall all the changes I made to get it working but I could probably go through it and find out.

**Comment by lolzitos** [comment]
@Corran-Raisu it will be great to show us how to revert it. Thanks!

**Comment by Corran-Raisu** [comment]
Go to Commit 783740e <-- is clickable.
Click Browse Code
Click Download ZIP

Copy the "RiotSharp-783740e49b1127e15e9f8d2d4e03d6ac2f53eebc" folder to your hard drive.
Open "RiotSharp.sln"

Add to GameEndpoint/GameSubType.cs

        /// <summary>
        /// King Poro mode games.
        /// </summary>
        KingPoro

--------------------------------------------------------

Add to GameEndpoint/GameSubTypeConverter.cs

                    case "KING_PORO":
                        return GameSubType.KingPoro;

and

                case GameSubType.KingPoro:
                    result =  "KING_PORO";
                    break;

--------------------------------------------------------

Add to MatchEndpoint/QueueType.cs

        /// <summary>
        /// Ascension games 5vs5
        /// </summary>
        Ascension_5x5,

        /// <summary>
        /// Twisted Treeline games 6vs6.
        /// </summary>
        Hexakill,

        /// <summary>
        /// King Poro games 5vs5.
        /// </summary>
        KingPoro5x5

and

                case QueueType.Ascension_5x5:
                    return "ASCENSION_5x5";
                case QueueType.Hexakill:
                    return "HEXAKILL";
                case QueueType.KingPoro5x5:
                    return "KING_PORO_5x5";

Isn't this case statement part of the converter? If following the same structure as the other I mean.  Oh well.

--------------------------------------------------------

Add to MatchEndpoint/QueueTypeConverter.cs

                    case "ASCENSION_5x5":
                        return QueueType.Ascension_5x5;
                    case "HEXAKILL":
                        return QueueType.Hexakill;
                    case "KING_PORO_5x5":
                        return QueueType.KingPoro5x5;

--------------------------------------------------------

Add to Misc/GameMode.cs

        /// <summary>
        /// Intro games.
        /// </summary>
        Intro,

        /// <summary>
        /// King Poro games.
        /// </summary>
        KingPoro

--------------------------------------------------------

Add to Misc/GameModeconverter

                    case "INTRO":
                        return GameMode.Intro;
                    case "KINGPORO":
                        return GameMode.KingPoro;

and

                case GameMode.Intro:
                    result = "INTRO";
                    break;
                case GameMode.KingPoro:
                    result = "KINGPORO";
                    break;

--------------------------------------------------------
--------------------------------------------------------

I believe that was everything I could find.

**Comment by lolzitos** [comment]
@Corran-Raisu , many thanks for you help! it work perfectly! :)

**Comment by AKlitbo** [comment]
@Corran-Raisu, awesome but you missed a spot. 

Add to StatsEndpoint/PlayerStatsSummaryType
>KingPoro

Add to StatsEndpoint/PlayerStatsSummaryTypeConverter
>case "KingPoro":
                        return PlayerStatsSummaryType.KingPoro;

**Comment by Corran-Raisu** [comment]
I haven't actually touched those Endpoints and I assume @lolzitos hasn't either since those haven't caused any errors yet.

I've only pulled the detailed information so summaries do me no good :smile:

**Comment by BenFradet** [comment]
This should be fixed now, I'm going to create a nuget soon.

**Comment by BenFradet** [comment]
Nuget uploaded

**Comment by itapi** [comment]
@BenFradet  ty man!!!!!!!!!!!!! we all appreicate ur amazing work!!

**Comment by BenFradet** [comment]
Glad to hear that.

**Comment by lolzitos** [comment]
@BenFradet We really apreciate your effort! :) pretty soon a beta test of my web application and of course will be a mention to RiotSharp  ;)

**Comment by BenFradet** [comment]
Thanks man.
