### ISSUE TITLE
getting champ name.... please help

### ISSUE THREAD

**Issue by itapi** [BenFradet/RiotSharp#93]
@BenFradet  hey bro i just download ur previous library and its woorking great .

im just trying a simple code to get the new free champ of the week names...
this is the code..

            var api = RiotApi.GetInstance("2549a36f-ad08-4774-8097-40867bd001e4");

         
            
   
            List<Champion> champlist = new List<Champion>();

                                  
            champlist = api.GetChampions(RiotSharp.Region.eune);

         
            foreach (Champion champ in champlist)
            {

            
                if (champ.FreeToPlay)
                {

                 
                   MessageBox.Show( champ. name);
               

                   
                }

            }

but there is one problem... there is no any name feature... like i cant acess the name.. only the id...

any idea how can i get the name in another way? :cry: 

just tried to use some champstatic or champstatcdata classes.. but didnt work well..
i dont know exactly how to use em... so please help? :smiley:

**Comment by BenFradet** [comment]
Yeah that's normal, you need to use the static api in order to get information on champions:

```c#
var staticApi = StaticRiotApi.GetInstance(apiKey);
// to get results about Annie
var champ = api.GetChampion(Region.euw, 1, ChampionData.all);
```

**Comment by itapi** [comment]
@BenFradet 

ty for the help man but now there is another error...

 var cp = api.GetChampion(RiotSharp.Region.eune, 1, ChampionData.all);


the method getchampion doesnt take 3 argurments...

**Comment by BenFradet** [comment]
Make sure you're using the static api and not the usual api.
