### ISSUE TITLE
ERROR, installing RiotSharp

### ISSUE THREAD

**Issue by Eniplay** [BenFradet/RiotSharp#98]
Hello, 
I wanted to download RiotSharp from the Nuget Package Manager Console but i can't.
It always shows this error message:
"
Install-Package : Could not install package 'RiotSharp 2.1.5'. You are trying to install this package into a project that targets .NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  RiotSharp
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
"
obviously, my framework does not match with RiotSharp. Im using Visual Studio 2010 and framework 4.0 is the last one i can get.
maybe u can help me

**Comment by XeeX** [comment]
RiotSharp uses the .net 4.5 for the async keyword. I'm afraid @BenFradet won't be able to help you until someone decides to rebuild everything for .net 4.0

**Comment by Eniplay** [comment]
Well, I thik there is no need to rebuild it. 
I will buy Visual Studio 2015 who's compatible with .net 4.5 <
But really thx for the Information :)

**Comment by XeeX** [comment]
No need to buy Visual Studio 2015 (which is in preview atm). You can download for **free** (and legally) [Visual Studio Community 2013](http://www.visualstudio.com/en-us/products/visual-studio-community-vs).

**Comment by Eniplay** [comment]
Oh wow, Well thank you very much man ^^

**Comment by BenFradet** [comment]
Yup, exactly as @XeeX said, feel free to close the issue.
