### ISSUE TITLE
Error get Summoner ID

### ISSUE THREAD

**Issue by Eniplay** [BenFradet/RiotSharp#99]
Hey,

i know, there are several questions about why .getSummoner doesnt work. But i saw that everyone who has this problem got it fixed. But not me. 
I have following Code:

![unbenannt](https://cloud.githubusercontent.com/assets/10630916/5855156/40630e40-a235-11e4-8164-07eb3cc123d3.png)

When i press the button the programm just freezes with no chance to do something like the other users sayed. 
Maybe i am just dumb and did it all wrong. In case of that u can punish me for that im such a bad Programmer ^^.

Welkl hope u can help me

**Comment by BenFradet** [comment]
Hey, which version of the nuget are you using?

**Comment by Eniplay** [comment]
I'm using Version... Let me see...: 2.1.5
 .Net Framework Version 4.5

**Comment by BenFradet** [comment]
Ok, I'll check in a couple of hours.

**Comment by Eniplay** [comment]
Thank you very much :)

**Comment by BenFradet** [comment]
Hey, I set up an application similar to yours and I haven't been able to reproduce the issue.
Could you try with the latest version of the nuget (2.1.6)?

**Comment by Eniplay** [comment]
Hey, yes i will try it. thanks

**Comment by Eniplay** [comment]
Well now it works fine. Very very thanks to you :)

**Comment by BenFradet** [comment]
No problem, glad I could help.
